"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useI18n } from "../../../language-provider";
import { AmazonWorkbenchRecommendation } from "../../../amazon-recommendations";

type Work = { id: string; title: string; description: string; genre: string; language: string; premise: string; styleGuide: string; referenceExcerpt: string; isPublished: boolean; slug: string; updatedAt: string };
type Volume = { id: string; workId: string; position: number; title: string; synopsis: string };
type Chapter = { id: string; workId: string; volumeId: string; position: number; title: string; outline: string; content: string; targetWords: number; status: string; isPublished: boolean; revision: number; updatedAt: string };
type Character = { id: string; name: string; role: string; description: string; personality: string; goal: string };
type Relationship = { id: string; sourceCharacterId: string; targetCharacterId: string; relationship: string; description: string };
type WorldEntry = { id: string; category: string; title: string; content: string; isHardSetting: boolean };
type TimelineEvent = { id: string; position: number; timeLabel: string; title: string; content: string };
type LogicLink = { id: string; fromRef: string; relation: string; toRef: string; notes: string; status: string };
type Bundle = { volumes: Volume[]; chapters: Chapter[]; characters: Character[]; relationships: Relationship[]; world: WorldEntry[]; timeline: TimelineEvent[]; logicLinks: LogicLink[] };

export function Workbench({ initialWork, initialBundle }: { initialWork: Work; initialBundle: Bundle }) {
  const { locale, t } = useI18n();
  const [work, setWork] = useState(initialWork);
  const [volumes, setVolumes] = useState(initialBundle.volumes);
  const [chapters, setChapters] = useState(initialBundle.chapters);
  const [bundle, setBundle] = useState(initialBundle);
  const [selectedId, setSelectedId] = useState(initialBundle.chapters[0]?.id ?? "");
  const [expanded, setExpanded] = useState(() => new Set(initialBundle.volumes.map((item) => item.id)));
  const [draft, setDraft] = useState(() => initialBundle.chapters[0] ?? null);
  const [saveState, setSaveState] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const [contextTab, setContextTab] = useState<"characters" | "world" | "timeline" | "logic">("characters");
  const [promptOpen, setPromptOpen] = useState(false);
  const [addDialog, setAddDialog] = useState<{ type: "volume" | "chapter"; volumeId?: string } | null>(null);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [contextOpen, setContextOpen] = useState(false);
  const [exportOpen, setExportOpen] = useState(false);
  const [selectedExportVolumes, setSelectedExportVolumes] = useState(() => new Set(initialBundle.volumes.map((item) => item.id)));
  const [exportIncludeToc, setExportIncludeToc] = useState(true);
  const [exportIncludePremise, setExportIncludePremise] = useState(false);
  const [exportIncludeVolumeSynopses, setExportIncludeVolumeSynopses] = useState(false);
  const [exportTraditional, setExportTraditional] = useState(initialWork.language.toLowerCase().startsWith("zh-tw"));
  const selected = chapters.find((item) => item.id === selectedId) ?? null;
  const selectedVolume = volumes.find((item) => item.id === selected?.volumeId);
  const wordCount = draft?.content.trim() ? draft.content.trim().split(/\s+|(?<=[\u3400-\u9fff\u3040-\u30ff])/).filter(Boolean).length : 0;

  function chooseChapter(chapter: Chapter) { setSelectedId(chapter.id); setDraft(chapter); setSaveState("idle"); }
  function toggleVolume(id: string) { setExpanded((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  async function saveChapter() {
    if (!draft) return; setSaveState("saving");
    const response = await fetch(`/api/works/${work.id}/chapters/${draft.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: draft.title, outline: draft.outline, content: draft.content, targetWords: draft.targetWords, isPublished: draft.isPublished, status: draft.content.trim() ? "draft" : "outline", revision: draft.revision }) });
    const result = await response.json() as { chapter?: Chapter };
    if (!response.ok || !result.chapter) { setSaveState("error"); return; }
    setDraft(result.chapter); setChapters((items) => items.map((item) => item.id === result.chapter!.id ? result.chapter! : item)); setSaveState("saved");
  }
  async function addOutline(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!addDialog) return;
    const values = Object.fromEntries(new FormData(event.currentTarget));
    const response = await fetch(`/api/works/${work.id}/outline`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...values, type: addDialog.type, volumeId: addDialog.volumeId }) });
    const result = await response.json() as { volume?: Volume; chapter?: Chapter };
    if (result.volume) { setVolumes((items) => [...items, result.volume!]); setExpanded((items) => new Set([...items, result.volume!.id])); }
    if (result.chapter) { setChapters((items) => [...items, result.chapter!]); setExpanded((items) => new Set([...items, result.chapter!.volumeId])); chooseChapter(result.chapter); }
    setAddDialog(null);
  }
  async function saveSettings(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget));
    const response = await fetch(`/api/works/${work.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...values, isPublished: values.isPublished === "on" }) });
    const result = await response.json() as { work?: Work };
    if (result.work) setWork(result.work); setSettingsOpen(false);
  }
  const prompt = useMemo(() => draft ? buildPrompt(work, selectedVolume, draft, bundle) : "", [work, selectedVolume, draft, bundle]);
  const isChineseBook = work.language.toLowerCase().startsWith("zh");
  const selectedExportParam = [...selectedExportVolumes].join(",");
  function openExport() { setSelectedExportVolumes(new Set(volumes.map((item) => item.id))); setExportOpen(true); }
  function exportHref(format: "docx" | "markdown" | "print") {
    const query = new URLSearchParams({ volumes: selectedExportParam, toc: String(exportIncludeToc), premise: String(exportIncludePremise), volumeSynopsis: String(exportIncludeVolumeSynopses), script: exportTraditional ? "traditional" : "original" });
    return format === "print" ? `/studio/works/${work.id}/print?${query}` : `/api/works/${work.id}/export?format=${format}&${query}`;
  }

  return <div className="workbench"><header className="workbench-head"><div className="work-crumb"><Link href="/studio">{t("work.myWorks")}</Link><span>›</span><b>{work.title}</b><span className={work.isPublished ? "published-dot" : "draft-dot"}>{work.isPublished ? t("work.public") : t("work.private")}</span></div><div><span className={`save-state ${saveState}`}>{saveState === "saving" ? t("work.saving") : saveState === "saved" ? t("work.saved") : saveState === "error" ? t("work.saveFailed") : ""}</span><button className="studio-button quiet" onClick={openExport}>{t("work.export")}</button><button className="studio-button quiet" onClick={() => setSettingsOpen(true)}>{t("work.settings")}</button>{work.isPublished && <Link className="studio-button quiet" href={`/read/${work.slug}`}>{t("work.readPage")}</Link>}<button className="studio-button primary" onClick={saveChapter}>{t("work.saveChapter")}</button></div></header>
    <div className="workbench-grid"><aside className="outline-panel"><div className="panel-title"><div><span>{t("work.manuscript")}</span><b>{t("work.outline")}</b></div><button className="round-add" onClick={() => setAddDialog({ type: "volume" })} title={t("work.addVolume")}>＋</button></div><div className="outline-tree">{volumes.map((volume) => <div className="volume-node" key={volume.id}><div className="volume-row"><button onClick={() => toggleVolume(volume.id)}>{expanded.has(volume.id) ? "⌄" : "›"}<span>{t("work.volume",{number:volume.position})}</span><b>{volume.title}</b></button><button className="node-add" title={t("work.addChapter")} onClick={() => setAddDialog({ type: "chapter", volumeId: volume.id })}>＋</button></div>{expanded.has(volume.id) && <div className="chapter-nodes">{chapters.filter((chapter) => chapter.volumeId === volume.id).sort((a,b) => a.position-b.position).map((chapter) => <button className={chapter.id === selectedId ? "active" : ""} onClick={() => chooseChapter(chapter)} key={chapter.id}><span>{String(chapter.position).padStart(2,"0")}</span><div><b>{chapter.title}</b><small>{chapter.content.trim() ? `${countWords(chapter.content).toLocaleString(locale)} ${t("dashboard.wordUnit")}` : t("work.notStarted")}{chapter.isPublished ? ` · ${t("work.chapterPublished")}` : ""}</small></div><i className={chapter.content.trim() ? "has-draft" : ""} /></button>)}</div>}</div>)}</div><div className="outline-foot"><span>{volumes.length} {t("work.volumes")}</span><span>{chapters.length} {t("dashboard.chapterUnit")}</span><span>{chapters.reduce((sum,item) => sum+countWords(item.content),0).toLocaleString(locale)} {t("dashboard.wordUnit")}</span></div></aside>
      <main className="editor-panel">{draft ? <><div className="chapter-context"><div><small>LATEST OUTLINE · V{draft.revision}</small><input aria-label={t("work.chapterTitle")} value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></div><label>{t("work.targetWords")}<input type="number" min={100} max={30000} value={draft.targetWords} onChange={(event) => setDraft({ ...draft, targetWords: Number(event.target.value) })} /></label></div><textarea className="outline-input" aria-label={t("work.chapterOutline")} value={draft.outline} onChange={(event) => setDraft({ ...draft, outline: event.target.value })} placeholder={t("work.outlinePlaceholder")} /><div className="editor-toolbar"><button className="ai-compose" onClick={() => setPromptOpen(true)}>{t("work.aiPrompt")}</button><div><span>{wordCount.toLocaleString(locale)} / {draft.targetWords.toLocaleString(locale)} {t("dashboard.wordUnit")}</span><label className="publish-check"><input type="checkbox" checked={draft.isPublished} onChange={(event) => setDraft({ ...draft, isPublished: event.target.checked })} />{t("work.publishChapter")}</label></div></div><textarea className="manuscript-editor" aria-label={t("work.body")} spellCheck value={draft.content} onChange={(event) => { setDraft({ ...draft, content: event.target.value }); setSaveState("idle"); }} placeholder={t("work.bodyPlaceholder")} /></> : <div className="editor-empty">{t("work.addFirst")}</div>}</main>
      <aside className="context-panel"><div className="context-heading"><div><span>{t("work.context")}</span><small>{t("work.contextAuto")}</small></div><button onClick={() => setContextOpen(true)}>{t("work.manage")}</button></div><div className="context-tabs"><button className={contextTab === "characters" ? "active" : ""} onClick={() => setContextTab("characters")}>{t("work.characters")}</button><button className={contextTab === "world" ? "active" : ""} onClick={() => setContextTab("world")}>{t("work.settingsTab")}</button><button className={contextTab === "timeline" ? "active" : ""} onClick={() => setContextTab("timeline")}>{t("work.time")}</button><button className={contextTab === "logic" ? "active" : ""} onClick={() => setContextTab("logic")}>{t("work.logic")}</button></div><ContextList tab={contextTab} bundle={bundle} /><AmazonWorkbenchRecommendation /><div className="context-note"><b>{t("work.privacyTitle")}</b><p>{t("work.privacyBody")}</p></div></aside>
    </div>
    {promptOpen && <div className="prompt-drawer"><div className="prompt-drawer-head"><div><span className="studio-kicker">EXTERNAL AI PROMPT</span><h2>{t("work.promptTitle")}</h2><p>{t("work.promptBody")}</p></div><button aria-label={t("common.close")} onClick={() => setPromptOpen(false)}>×</button></div><textarea value={prompt} readOnly /><div className="prompt-actions"><span>{t("work.promptPrivacy")}</span><button className="studio-button primary" onClick={async () => { await navigator.clipboard.writeText(prompt); }}>{t("work.copyPrompt")}</button></div></div>}
    {addDialog && <div className="modal-backdrop" onMouseDown={(event) => { if (event.currentTarget === event.target) setAddDialog(null); }}><section className="studio-modal"><button className="modal-close" aria-label={t("common.close")} onClick={() => setAddDialog(null)}>×</button><span className="studio-kicker">{addDialog.type === "volume" ? t("work.newVolume") : t("work.newChapter")}</span><h2>{addDialog.type === "volume" ? t("work.addOneVolume") : t("work.addOneChapter")}</h2><form onSubmit={addOutline}><label>{t("work.title")}<input required name="title" autoFocus placeholder={addDialog.type === "volume" ? t("work.volumeTitlePlaceholder") : t("work.chapterTitlePlaceholder")} /></label><label>{addDialog.type === "volume" ? t("work.volumeSynopsis") : t("work.chapterOutline")}<textarea rows={5} name={addDialog.type === "volume" ? "synopsis" : "outline"} placeholder={t("work.goalConflict")} /></label><div className="modal-actions"><button type="button" className="studio-button quiet" onClick={() => setAddDialog(null)}>{t("common.cancel")}</button><button className="studio-button primary">{t("common.add")}</button></div></form></section></div>}
    {settingsOpen && <div className="modal-backdrop" onMouseDown={(event) => { if (event.currentTarget === event.target) setSettingsOpen(false); }}><section className="studio-modal settings-modal"><button className="modal-close" aria-label={t("common.close")} onClick={() => setSettingsOpen(false)}>×</button><span className="studio-kicker">{t("work.settingsKicker")}</span><h2>{t("work.foundation")}</h2><form onSubmit={saveSettings}><label>{t("dashboard.workTitle")}<input name="title" defaultValue={work.title} required /></label><div className="field-row"><label>{t("work.genre")}<input name="genre" defaultValue={work.genre} /></label><label>{t("work.language")}<input name="language" defaultValue={work.language} /></label></div><label>{t("work.description")}<textarea name="description" rows={3} defaultValue={work.description} /></label><label>{t("work.premise")}<textarea name="premise" rows={4} defaultValue={work.premise} /></label><label>{t("work.style")}<textarea name="styleGuide" rows={5} defaultValue={work.styleGuide} /></label><label>{t("work.reference")}<textarea name="referenceExcerpt" rows={5} defaultValue={work.referenceExcerpt} /></label><label className="publish-setting"><input type="checkbox" name="isPublished" defaultChecked={work.isPublished} /><span><b>{t("work.publishPage")}</b><small>{t("work.publishPageBody")}</small></span></label><div className="modal-actions"><button type="button" className="studio-button quiet" onClick={() => setSettingsOpen(false)}>{t("common.cancel")}</button><button className="studio-button primary">{t("work.saveSettings")}</button></div></form></section></div>}
    {exportOpen && <div className="modal-backdrop export-backdrop" onMouseDown={(event) => { if (event.currentTarget === event.target) setExportOpen(false); }}><section className="studio-modal export-modal"><button className="modal-close" aria-label={t("common.close")} onClick={() => setExportOpen(false)}>×</button><span className="studio-kicker">EXPORT</span><h2>{t("export.title")} · {work.title}</h2><p>{t("export.intro")}</p>
      {isChineseBook && <div className="export-script"><b>{t("export.outputScript")}</b><div><button className={!exportTraditional ? "active" : ""} onClick={() => setExportTraditional(false)}>{t("export.originalChinese")}</button><button className={exportTraditional ? "active" : ""} onClick={() => setExportTraditional(true)}>{t("export.traditionalChinese")}</button></div><small>{t("export.scriptHelp")}</small></div>}
      <section className="export-volume-picker"><header><b>{t("export.selectVolumes")}</b><button onClick={() => setSelectedExportVolumes(selectedExportVolumes.size === volumes.length ? new Set() : new Set(volumes.map((item) => item.id)))}>{selectedExportVolumes.size === volumes.length ? t("export.deselectAll") : t("export.selectAll")}</button></header><div>{volumes.map((volume) => { const volumeChapters=chapters.filter((chapter)=>chapter.volumeId===volume.id); const words=volumeChapters.reduce((sum,chapter)=>sum+countWords(chapter.content),0); return <label key={volume.id}><input type="checkbox" checked={selectedExportVolumes.has(volume.id)} onChange={() => setSelectedExportVolumes((current) => { const next=new Set(current); if(next.has(volume.id))next.delete(volume.id);else next.add(volume.id); return next; })}/><span><b>{volume.title}</b><small>{volumeChapters.length} {t("dashboard.chapterUnit")} · {words.toLocaleString(locale)} {t("dashboard.wordUnit")}</small></span></label>;})}</div></section>
      <div className="export-checks"><label><input type="checkbox" checked={exportIncludeToc} onChange={(event)=>setExportIncludeToc(event.target.checked)}/><span><b>{t("export.includeToc")}</b><small>{t("export.tocHelp")}</small></span></label><label><input type="checkbox" checked={exportIncludePremise} onChange={(event)=>setExportIncludePremise(event.target.checked)}/><span><b>{t("export.includePremise")}</b><small>{t("export.premiseHelp")}</small></span></label><label><input type="checkbox" checked={exportIncludeVolumeSynopses} onChange={(event)=>setExportIncludeVolumeSynopses(event.target.checked)}/><span><b>{t("export.includeVolumeSynopses")}</b><small>{t("export.volumeHelp")}</small></span></label></div>
      <div className="export-formats"><a className={!selectedExportVolumes.size?"disabled":""} aria-disabled={!selectedExportVolumes.size} href={selectedExportVolumes.size?exportHref("docx"):undefined} onClick={() => selectedExportVolumes.size && setExportOpen(false)}><i>W</i><span><b>{t("export.word")}</b><small>{t("export.wordHelp")}</small></span><em>›</em></a><a className={!selectedExportVolumes.size?"disabled":""} aria-disabled={!selectedExportVolumes.size} href={selectedExportVolumes.size?exportHref("print"):undefined} target="_blank" rel="noreferrer" onClick={() => selectedExportVolumes.size && setExportOpen(false)}><i>PDF</i><span><b>{t("export.pdf")}</b><small>{t("export.pdfHelp")}</small></span><em>›</em></a><a className={!selectedExportVolumes.size?"disabled":""} aria-disabled={!selectedExportVolumes.size} href={selectedExportVolumes.size?exportHref("markdown"):undefined} onClick={() => selectedExportVolumes.size && setExportOpen(false)}><i>MD</i><span><b>{t("export.markdown")}</b><small>{t("export.markdownHelp")}</small></span><em>›</em></a><a href={`/api/works/${work.id}/backup`} onClick={()=>setExportOpen(false)}><i>JSON</i><span><b>{t("export.backup")}</b><small>{t("export.backupHelp")}</small></span><em>›</em></a></div>
      <footer className="export-note">{t("export.selected",{selected:selectedExportVolumes.size,total:volumes.length})} · {t("export.filename")}</footer>
    </section></div>}
    {contextOpen && <ContextManager workId={work.id} bundle={bundle} onClose={() => setContextOpen(false)} onChange={setBundle} />}
  </div>;
}

function ContextList({ tab, bundle }: { tab: "characters" | "world" | "timeline" | "logic"; bundle: Bundle }) {
  const { t } = useI18n();
  if (tab === "characters") return <div className="context-list">{bundle.characters.length ? bundle.characters.map((item) => <article key={item.id}><span className="context-avatar">{item.name.slice(0,1)}</span><div><b>{item.name}</b><small>{item.role || t("memory.personFallback")}</small><p>{item.personality || item.description || t("memory.noDescription")}</p></div></article>) : <EmptyContext text={t("memory.noCharacters")} />}</div>;
  if (tab === "world") return <div className="context-list simple">{bundle.world.length ? bundle.world.map((item) => <article key={item.id}><div><b>{item.title}{item.isHardSetting && <em>{t("memory.hardBadge")}</em>}</b><small>{item.category}</small><p>{item.content}</p></div></article>) : <EmptyContext text={t("memory.noWorld")} />}</div>;
  if (tab === "timeline") return <div className="context-list simple">{bundle.timeline.length ? bundle.timeline.map((item) => <article key={item.id}><div><b>{item.title}</b><small>{item.timeLabel || t("memory.orderValue",{number:item.position})}</small><p>{item.content}</p></div></article>) : <EmptyContext text={t("memory.noTimeline")} />}</div>;
  return <div className="context-list simple">{bundle.logicLinks.length ? bundle.logicLinks.map((item) => <article key={item.id}><div><b>{item.fromRef} → {item.toRef}</b><small>{item.relation}</small><p>{item.notes}</p></div></article>) : <EmptyContext text={t("memory.noLogic")} />}</div>;
}

type ContextKind = "character" | "relationship" | "world" | "timeline" | "logic";
type ContextItem = Character | Relationship | WorldEntry | TimelineEvent | LogicLink;

function ContextManager({ workId, bundle, onClose, onChange }: { workId: string; bundle: Bundle; onClose: () => void; onChange: React.Dispatch<React.SetStateAction<Bundle>> }) {
  const { t } = useI18n();
  const [tab, setTab] = useState<ContextKind>("character");
  const [editing, setEditing] = useState<{ kind: ContextKind; item: ContextItem } | null>(null);
  const [jsonOpen, setJsonOpen] = useState(false);
  const [error, setError] = useState("");
  const rows: Record<ContextKind, ContextItem[]> = { character: bundle.characters, relationship: bundle.relationships, world: bundle.world, timeline: bundle.timeline, logic: bundle.logicLinks };
  function switchTab(kind: ContextKind) { setTab(kind); setEditing(null); setError(""); }
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); const values=Object.fromEntries(new FormData(event.currentTarget)); const method=editing?"PATCH":"POST";
    const response=await fetch(`/api/works/${workId}/context`,{method,headers:{"content-type":"application/json"},body:JSON.stringify({...values,kind:tab,id:editing?.item.id,isHardSetting:values.isHardSetting==="on"})});
    const result=await response.json() as {item?:ContextItem;error?:string}; if(!response.ok||!result.item){setError(result.error||t("memory.saveFailed"));return;}
    const key=contextKey(tab); onChange((current)=>({...current,[key]:editing?(current[key] as ContextItem[]).map((item)=>item.id===result.item!.id?result.item!:item):[...(current[key] as ContextItem[]),result.item!]}));
    setEditing(null); event.currentTarget.reset();
  }
  async function remove(item: ContextItem) {
    const response=await fetch(`/api/works/${workId}/context?kind=${tab}&itemId=${encodeURIComponent(item.id)}`,{method:"DELETE"});if(!response.ok)return;
    const key=contextKey(tab);onChange((current)=>({...current,[key]:(current[key] as ContextItem[]).filter((row)=>row.id!==item.id)}));if(editing?.item.id===item.id)setEditing(null);
  }
  const current=editing?.kind===tab?editing.item:null;
  const tabLabels: Record<ContextKind,string>={character:t("memory.character"),relationship:t("memory.relationship"),world:t("memory.world"),timeline:t("memory.timeline"),logic:t("memory.logic")};
  return <><div className="modal-backdrop context-manager-backdrop" onMouseDown={(event)=>{if(event.currentTarget===event.target)onClose();}}><section className="context-manager"><header><div><span className="studio-kicker">STORY MEMORY</span><h2>{t("memory.title")}</h2><p>{t("memory.intro")}</p></div><div className="context-manager-actions"><button className="context-json-button" onClick={()=>setJsonOpen(true)}>⇩ {t("memory.jsonImport")}</button><a className="context-json-button" href={`/api/works/${workId}/context-json`} download>⇧ {t("memory.jsonExport")}</a><button className="context-manager-close" aria-label={t("common.close")} onClick={onClose}>×</button></div></header><nav>{(Object.keys(tabLabels) as ContextKind[]).map((kind)=><button className={tab===kind?"active":""} key={kind} onClick={()=>switchTab(kind)}>{tabLabels[kind]}<span>{rows[kind].length}</span></button>)}</nav><div className="context-manager-body"><div className="context-edit-list">{rows[tab].length?rows[tab].map((item)=><article className={editing?.item.id===item.id?"active":""} key={item.id}><button onClick={()=>setEditing({kind:tab,item})}><b>{contextTitle(tab,item,bundle)}</b><span>{contextSubtitle(tab,item,t)}</span></button><button className="delete-context" onClick={()=>remove(item)}>{t("common.delete")}</button></article>):<div className="context-manager-empty">{t("memory.emptyCategory")}</div>}</div><form key={`${tab}-${current?.id||"new"}`} onSubmit={submit}><div className="context-form-title"><b>{current?t("memory.edit"):t("memory.add")}</b>{current&&<button type="button" onClick={()=>setEditing(null)}>{t("memory.cancelEdit")}</button>}</div><ContextFields kind={tab} item={current} characters={bundle.characters} />{error&&<p className="form-error">{error}</p>}<button className="studio-button primary">{current?t("memory.saveEdit"):t("common.add")}</button></form></div></section></div>{jsonOpen&&<MemoryJsonImport workId={workId} onClose={()=>setJsonOpen(false)} onImported={(next)=>{onChange(next);setJsonOpen(false);setEditing(null);}}/>}</>;
}

type JsonCategory = "characters" | "relationships" | "world" | "timeline" | "logicChains";
type JsonChange = "added" | "updated" | "unchanged" | "deleted";
type JsonPreview = { expectedUpdatedAt: string; summary: { category: JsonCategory; added: number; updated: number; unchanged: number; deleted: number }[]; items: { category: JsonCategory; label: string; change: JsonChange }[]; totalItems: number; truncated: boolean };

function MemoryJsonImport({ workId, onClose, onImported }: { workId: string; onClose: () => void; onImported: (bundle: Bundle) => void }) {
  const { t } = useI18n();
  const [text, setText] = useState("");
  const [preview, setPreview] = useState<JsonPreview | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const categoryLabels: Record<JsonCategory,string>={characters:t("memory.character"),relationships:t("memory.relationship"),world:t("memory.world"),timeline:t("memory.timeline"),logicChains:t("memory.logic")};
  const changeLabels: Record<JsonChange,string>={added:t("memory.jsonAdded"),updated:t("memory.jsonUpdated"),unchanged:t("memory.jsonUnchanged"),deleted:t("memory.jsonDeleted")};
  async function request(mode:"preview"|"apply") {
    setBusy(true);setError("");
    const response=await fetch(`/api/works/${workId}/context-json`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode,data:text,expectedUpdatedAt:preview?.expectedUpdatedAt,confirmReplace:mode==="apply"})});
    const result=await response.json() as (JsonPreview&{bundle?:Bundle;error?:string});setBusy(false);
    if(!response.ok){setError(result.error||t("memory.jsonFailed"));if(response.status===409)setPreview(null);return;}
    if(mode==="preview")setPreview(result);else if(result.bundle)onImported(result.bundle);
  }
  async function loadFile(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setText(await file.text());setPreview(null);setError("");}
  return <div className="modal-backdrop memory-json-backdrop" onMouseDown={(event)=>{if(event.currentTarget===event.target)onClose();}}><section className="studio-modal memory-json-modal"><button className="modal-close" aria-label={t("common.close")} onClick={onClose}>×</button><span className="studio-kicker">JSON · EXTERNAL AI</span><h2>{t("memory.jsonTitle")}</h2><p>{t("memory.jsonIntro")}</p><label className="memory-json-file">{t("memory.jsonFile")}<input type="file" accept="application/json,.json" onChange={loadFile}/></label><label>{t("memory.jsonPaste")}<textarea rows={13} value={text} onChange={(event)=>{setText(event.target.value);setPreview(null);}} placeholder={t("memory.jsonPlaceholder")}/></label><details className="memory-json-example"><summary>{t("memory.jsonExample")}</summary><div><button type="button" onClick={()=>navigator.clipboard.writeText(memoryJsonExample)}>{t("memory.jsonCopyExample")}</button><pre>{memoryJsonExample}</pre></div></details>{preview&&<div className="memory-json-preview"><h3>{t("memory.jsonPreviewTitle")}</h3><p>{t("memory.jsonReplaceNote")}</p><div className="memory-json-summary">{preview.summary.map((row)=><article key={row.category}><b>{categoryLabels[row.category]}</b><span className="added">{t("memory.jsonAdded")} {row.added}</span><span className="updated">{t("memory.jsonUpdated")} {row.updated}</span><span className="unchanged">{t("memory.jsonUnchanged")} {row.unchanged}</span><span className="deleted">{t("memory.jsonDeleted")} {row.deleted}</span></article>)}</div><div className="memory-json-items">{preview.items.filter((item)=>item.change!=="unchanged").map((item,index)=><div key={`${item.category}-${item.label}-${index}`}><span className={item.change}>{changeLabels[item.change]}</span><b>{categoryLabels[item.category]}</b><p>{item.label}</p></div>)}{preview.items.every((item)=>item.change==="unchanged")&&<p className="memory-json-no-change">{t("memory.jsonNoChanges")}</p>}{preview.truncated&&<p>{t("memory.jsonTruncated",{count:preview.totalItems})}</p>}</div></div>}{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button className="studio-button quiet" onClick={onClose}>{t("common.cancel")}</button>{!preview?<button className="studio-button primary" disabled={busy||!text.trim()} onClick={()=>request("preview")}>{busy?t("memory.jsonChecking"):t("memory.jsonPreview")}</button>:<><button className="studio-button quiet" disabled={busy} onClick={()=>setPreview(null)}>{t("memory.jsonEdit")}</button><button className="studio-button primary" disabled={busy} onClick={()=>request("apply")}>{busy?t("memory.jsonApplying"):t("memory.jsonApply")}</button></>}</div></section></div>;
}

const memoryJsonExample=JSON.stringify({schemaVersion:1,characters:[{name:"Mara Venn",role:"Protagonist",description:"A cartographer who can see erased roads.",personality:"Observant, stubborn, compassionate",goal:"Find the city removed from every map."},{name:"Ilan Roe",role:"Rival and reluctant ally",description:"An archivist employed by the Crown.",personality:"Controlled, skeptical, loyal",goal:"Protect the archive without repeating his father's betrayal."}],relationships:[{source:"Mara Venn",target:"Ilan Roe",relationship:"rivals to lovers",description:"Mutual distrust becomes dependence as each holds half of the truth."}],world:[{category:"Rule",title:"Erased roads",content:"A road disappears from maps one day before it vanishes from reality.",isHardSetting:true}],timeline:[{position:1,timeLabel:"Year 312, First Frost",title:"The northern road disappears",content:"Mara discovers her hometown has been cut off from recorded history."}],logicChains:[{fromRef:"The northern road disappears",relation:"forces",toRef:"Mara enters the Crown Archive",notes:"She needs the last map copied before the erasure.",status:"active"}]},null,2);

function ContextFields({ kind, item, characters }: { kind: ContextKind; item: ContextItem | null; characters: Character[] }) {
  const { t } = useI18n();
  if(kind==="character"){const value=item as Character|null;return <><label>{t("memory.name")}<input name="name" required defaultValue={value?.name}/></label><label>{t("memory.role")}<input name="role" defaultValue={value?.role} placeholder={t("memory.rolePlaceholder")}/></label><label>{t("memory.description")}<textarea name="description" rows={3} defaultValue={value?.description}/></label><label>{t("memory.personality")}<textarea name="personality" rows={2} defaultValue={value?.personality}/></label><label>{t("memory.goal")}<textarea name="goal" rows={2} defaultValue={value?.goal}/></label></>}
  if(kind==="relationship"){const value=item as Relationship|null;return <><label>{t("memory.source")}<select name="sourceCharacterId" required defaultValue={value?.sourceCharacterId||""}><option value="">{t("memory.select")}</option>{characters.map((person)=><option value={person.id} key={person.id}>{person.name}</option>)}</select></label><label>{t("memory.target")}<select name="targetCharacterId" required defaultValue={value?.targetCharacterId||""}><option value="">{t("memory.selectTarget")}</option>{characters.map((person)=><option value={person.id} key={person.id}>{person.name}</option>)}</select></label><label>{t("memory.relationshipType")}<input name="relationship" required defaultValue={value?.relationship} placeholder={t("memory.relationshipPlaceholder")}/></label><label>{t("memory.relationshipNotes")}<textarea name="description" rows={4} defaultValue={value?.description}/></label></>}
  if(kind==="world"){const value=item as WorldEntry|null;return <><div className="field-row"><label>{t("memory.entryName")}<input name="title" required defaultValue={value?.title}/></label><label>{t("memory.category")}<input name="category" defaultValue={value?.category} placeholder={t("memory.categoryPlaceholder")}/></label></div><label>{t("memory.details")}<textarea name="content" rows={6} defaultValue={value?.content}/></label><label className="inline-check"><input type="checkbox" name="isHardSetting" defaultChecked={value?.isHardSetting}/><span>{t("memory.hard")}</span></label></>}
  if(kind==="timeline"){const value=item as TimelineEvent|null;return <><div className="field-row"><label>{t("memory.order")}<input type="number" name="position" min="1" defaultValue={value?.position||1}/></label><label>{t("memory.storyTime")}<input name="timeLabel" defaultValue={value?.timeLabel} placeholder={t("memory.timePlaceholder")}/></label></div><label>{t("memory.eventName")}<input name="title" required defaultValue={value?.title}/></label><label>{t("memory.eventDetails")}<textarea name="content" rows={5} defaultValue={value?.content}/></label></>}
  const value=item as LogicLink|null;return <><label>{t("memory.cause")}<input name="fromRef" required defaultValue={value?.fromRef}/></label><label>{t("memory.relation")}<input name="relation" required defaultValue={value?.relation} placeholder={t("memory.relationPlaceholder")}/></label><label>{t("memory.result")}<input name="toRef" required defaultValue={value?.toRef}/></label><label>{t("memory.notes")}<textarea name="notes" rows={4} defaultValue={value?.notes}/></label></>;
}

function contextKey(kind:ContextKind):keyof Bundle{return kind==="character"?"characters":kind==="relationship"?"relationships":kind==="world"?"world":kind==="timeline"?"timeline":"logicLinks";}
function contextTitle(kind:ContextKind,item:ContextItem,bundle:Bundle){if(kind==="character")return(item as Character).name;if(kind==="relationship"){const value=item as Relationship;return`${bundle.characters.find((person)=>person.id===value.sourceCharacterId)?.name||"?"} → ${bundle.characters.find((person)=>person.id===value.targetCharacterId)?.name||"?"}`;}if(kind==="world")return(item as WorldEntry).title;if(kind==="timeline")return(item as TimelineEvent).title;const value=item as LogicLink;return`${value.fromRef} → ${value.toRef}`;}
function contextSubtitle(kind:ContextKind,item:ContextItem,t:(key:string,vars?:Record<string,string|number>)=>string){if(kind==="character")return(item as Character).role||t("memory.personFallback");if(kind==="relationship")return(item as Relationship).relationship;if(kind==="world")return(item as WorldEntry).category;if(kind==="timeline")return(item as TimelineEvent).timeLabel||t("memory.orderValue",{number:(item as TimelineEvent).position});return(item as LogicLink).relation;}

function EmptyContext({ text }: { text: string }) { return <div className="context-empty">{text}</div>; }
function countWords(value: string) { return value.trim() ? value.trim().split(/\s+|(?<=[\u3400-\u9fff\u3040-\u30ff])/).filter(Boolean).length : 0; }

const localePrompts: Record<string, { role: string; instruction: string; rules: string }> = {
  en: { role: "You are a professional long-form fiction writer.", instruction: "Write the complete chapter from the outline and context below.", rules: "Do not add a chapter heading. Preserve continuity and hard settings. Output only the chapter prose." },
  de: { role: "Du bist ein professioneller Autor für lange Romane.", instruction: "Schreibe das vollständige Kapitel anhand der folgenden Gliederung und des Kontexts.", rules: "Füge keine Kapitelüberschrift hinzu. Bewahre Kontinuität und feste Weltregeln. Gib nur den Kapiteltext aus." },
  es: { role: "Eres un novelista profesional de ficción larga.", instruction: "Escribe el capítulo completo a partir del esquema y el contexto siguientes.", rules: "No añadas el título del capítulo. Mantén la continuidad y las reglas fijas del mundo. Devuelve solo la prosa." },
  fr: { role: "Vous êtes un romancier professionnel spécialisé dans les récits longs.", instruction: "Rédigez le chapitre complet à partir du plan et du contexte ci-dessous.", rules: "N'ajoutez pas de titre de chapitre. Respectez la continuité et les règles immuables. Retournez uniquement le texte du chapitre." },
  ja: { role: "あなたは長編小説を執筆するプロの作家です。", instruction: "以下のプロットと文脈に基づいて、章全体を書いてください。", rules: "章タイトルを付けず、連続性と厳格な世界設定を守り、本文のみを出力してください。" },
  pt: { role: "Você é um romancista profissional de ficção longa.", instruction: "Escreva o capítulo completo com base no esboço e no contexto abaixo.", rules: "Não adicione o título do capítulo. Preserve a continuidade e as regras rígidas do mundo. Retorne apenas a prosa." },
  ko: { role: "당신은 장편소설을 쓰는 전문 작가입니다.", instruction: "아래 개요와 맥락을 바탕으로 완전한 장을 작성하세요.", rules: "장 제목을 추가하지 말고, 연속성과 확정 설정을 지키며, 본문만 출력하세요." },
  zh: { role: "你是一名专业的长篇小说作家。", instruction: "请根据下面的大纲与上下文，写出完整章节。", rules: "不要输出章节标题；保持前后连续，严格遵守硬设定；只输出正文。" },
};

function buildPrompt(work: Work, volume: Volume | undefined, chapter: Chapter, bundle: Bundle) {
  const key = Object.keys(localePrompts).find((item) => work.language.toLowerCase().startsWith(item)) ?? "zh";
  const language = localePrompts[key];
  const names = new Map(bundle.characters.map((item) => [item.id, item.name]));
  const charactersText = bundle.characters.map((item) => `- ${item.name} (${item.role || "role unspecified"}): ${item.description}\n  Personality: ${item.personality}\n  Goal: ${item.goal}`).join("\n") || "- None provided";
  const relationshipsText = bundle.relationships.map((item) => `- ${names.get(item.sourceCharacterId) || item.sourceCharacterId} —${item.relationship}→ ${names.get(item.targetCharacterId) || item.targetCharacterId}: ${item.description}`).join("\n") || "- None provided";
  const worldText = bundle.world.map((item) => `- [${item.isHardSetting ? "HARD" : item.category}] ${item.title}: ${item.content}`).join("\n") || "- None provided";
  const timelineText = bundle.timeline.map((item) => `- ${item.timeLabel || item.position} · ${item.title}: ${item.content}`).join("\n") || "- None provided";
  const logicText = bundle.logicLinks.map((item) => `- ${item.fromRef} —${item.relation}→ ${item.toRef}: ${item.notes}`).join("\n") || "- None provided";
  return `${language.role}\n\n${language.instruction}\n${language.rules}\nWrite in: ${work.language}\nTarget length: about ${chapter.targetWords} words/characters.\n\n# WORK\nTitle: ${work.title}\nGenre: ${work.genre}\nPremise: ${work.premise || work.description}\nStyle guide: ${work.styleGuide || "Follow the tone implied by the outline."}\nReference excerpt (imitate only high-level style, never copy phrases):\n${work.referenceExcerpt || "None provided"}\n\n# CURRENT LOCATION\nVolume ${volume?.position ?? "?"}: ${volume?.title ?? ""}\nVolume synopsis: ${volume?.synopsis ?? ""}\nChapter ${chapter.position}: ${chapter.title}\nChapter outline:\n${chapter.outline || "No outline provided; infer a restrained scene from the premise."}\n\n# CHARACTERS\n${charactersText}\n\n# RELATIONSHIPS\n${relationshipsText}\n\n# WORLD & BACKGROUND\n${worldText}\n\n# TIMELINE\n${timelineText}\n\n# LOGIC CHAINS\n${logicText}\n\n# FINAL CHECK\nMake every action causally motivated. Do not contradict established facts. End with forward momentum. Output only the chapter prose, without a heading or commentary.`;
}
