import { normalizeWritingLanguage, type WritingLanguageCode } from "@/lib/writing-languages";

export type ChapterPromptMode = "create" | "modify";

export type PromptWork = {
  title: string;
  description?: string | null;
  genre?: string | null;
  language?: string | null;
  premise?: string | null;
  styleGuide?: string | null;
  referenceExcerpt?: string | null;
};

export type PromptVolume = { id: string; position: number; title: string; synopsis?: string | null };
export type PromptChapter = { id: string; volumeId: string; position: number; title: string; outline?: string | null; content?: string | null; targetWords: number };
export type PromptBundle = {
  characters: { id: string; name: string; role?: string | null; description?: string | null; personality?: string | null; goal?: string | null }[];
  relationships: { sourceCharacterId: string; targetCharacterId: string; relationship?: string | null; description?: string | null }[];
  world: { category?: string | null; title: string; content?: string | null; isHardSetting: boolean }[];
  timeline: { position: number; timeLabel?: string | null; title: string; content?: string | null }[];
  logicLinks: { fromRef: string; relation: string; toRef: string; notes?: string | null }[];
};

type PromptLocale = {
  languageName: string; role: string; create: string; modify: string; rules: string; revisionRule: string;
  writeIn: string; targetLength: string; targetUnit: string;
  work: string; location: string; characters: string; relationships: string; world: string; timeline: string; logic: string; finalCheck: string;
  title: string; genre: string; premise: string; styleGuide: string; referenceExcerpt: string; referenceRule: string;
  volume: string; volumeSynopsis: string; chapter: string; chapterOutline: string;
  suggestion: string; currentDraft: string; enterSuggestion: string; noManuscript: string;
  unspecified: string; roleUnspecified: string; personality: string; goal: string; relatedTo: string; hard: string; setting: string; noneProvided: string;
  impliedStyle: string; noOutline: string; finalRule: string;
};

const localePrompts: Record<WritingLanguageCode, PromptLocale> = {
  en: {
    languageName: "English", role: "You are a professional long-form fiction writer.", create: "Write a complete new chapter from the outline and context below.", modify: "Revise the complete current chapter according to the author's suggestion below.", rules: "Do not add a chapter heading. Preserve continuity and hard settings. Output only the complete chapter prose.", revisionRule: "Keep effective passages unless the suggestion requires changing them. Resolve the requested issue throughout the chapter; return the full revised chapter, never a patch, summary, or explanation.",
    writeIn: "Writing language", targetLength: "Target length", targetUnit: "words/characters", work: "WORK", location: "CURRENT LOCATION", characters: "CHARACTERS", relationships: "RELATIONSHIPS", world: "WORLD & BACKGROUND", timeline: "TIMELINE", logic: "LOGIC CHAINS", finalCheck: "FINAL CHECK", title: "Title", genre: "Genre", premise: "Premise", styleGuide: "Style guide", referenceExcerpt: "Reference excerpt", referenceRule: "imitate only high-level style; never copy phrases", volume: "Volume", volumeSynopsis: "Volume synopsis", chapter: "Chapter", chapterOutline: "Chapter outline", suggestion: "AUTHOR'S REVISION SUGGESTION", currentDraft: "CURRENT CHAPTER MANUSCRIPT", enterSuggestion: "Enter a specific revision suggestion", noManuscript: "No current manuscript provided", unspecified: "Unspecified", roleUnspecified: "role unspecified", personality: "Personality", goal: "Goal", relatedTo: "related to", hard: "HARD", setting: "SETTING", noneProvided: "None provided", impliedStyle: "Follow the tone implied by the outline.", noOutline: "No outline provided; infer a restrained scene from the premise.", finalRule: "Make every action causally motivated. Do not contradict established facts. End with forward momentum. Output only the complete chapter prose, without a heading or commentary.",
  },
  "zh-CN": {
    languageName: "简体中文", role: "你是一名专业的长篇小说作家。", create: "请根据下面的大纲与上下文，创作一个完整的新章节。", modify: "请按照下面作者给出的修改建议，修改当前章节全文。", rules: "不要输出章节标题；保持前后连续，严格遵守硬设定；只输出完整正文。", revisionRule: "除非修改建议要求变动，否则保留已有的有效段落。修改必须贯穿全文并真正解决问题；请输出修改后的完整章节，不要输出差异、摘要或解释。",
    writeIn: "写作语言", targetLength: "目标篇幅", targetUnit: "字", work: "作品", location: "当前章节位置", characters: "人物", relationships: "人物关系", world: "世界观与背景", timeline: "时间线", logic: "逻辑链", finalCheck: "最终检查", title: "标题", genre: "类型", premise: "核心构想", styleGuide: "写作规则 / 风格指南", referenceExcerpt: "参考范本", referenceRule: "只模仿高层风格，绝不复制原句", volume: "卷", volumeSynopsis: "本卷介绍", chapter: "章", chapterOutline: "章节大纲", suggestion: "作者修改建议", currentDraft: "当前章节正文", enterSuggestion: "请输入具体修改建议", noManuscript: "尚未提供当前正文", unspecified: "未指定", roleUnspecified: "角色未指定", personality: "个性", goal: "目标", relatedTo: "相关", hard: "硬设定", setting: "设定", noneProvided: "暂无", impliedStyle: "遵循大纲所体现的语气。", noOutline: "未提供大纲；请根据核心构想推演一个克制的场景。", finalRule: "确保每个行动都有因果动机，不与既有事实冲突，并以推动后续情节的方式结尾。只输出完整章节正文，不要标题或解释。",
  },
  "zh-TW": {
    languageName: "繁體中文", role: "你是一名專業的長篇小說作家。", create: "請根據下面的大綱與上下文，創作一個完整的新章節。", modify: "請按照下面作者給出的修改建議，修改目前章節全文。", rules: "不要輸出章節標題；保持前後連續，嚴格遵守硬設定；只輸出完整正文。", revisionRule: "除非修改建議要求變動，否則保留已有的有效段落。修改必須貫穿全文並真正解決問題；請輸出修改後的完整章節，不要輸出差異、摘要或解釋。",
    writeIn: "寫作語言", targetLength: "目標篇幅", targetUnit: "字", work: "作品", location: "目前章節位置", characters: "人物", relationships: "人物關係", world: "世界觀與背景", timeline: "時間線", logic: "邏輯鏈", finalCheck: "最終檢查", title: "標題", genre: "類型", premise: "核心構想", styleGuide: "寫作規則 / 風格指南", referenceExcerpt: "參考範本", referenceRule: "只模仿高層風格，絕不複製原句", volume: "卷", volumeSynopsis: "本卷介紹", chapter: "章", chapterOutline: "章節大綱", suggestion: "作者修改建議", currentDraft: "目前章節正文", enterSuggestion: "請輸入具體修改建議", noManuscript: "尚未提供目前正文", unspecified: "未指定", roleUnspecified: "角色未指定", personality: "個性", goal: "目標", relatedTo: "相關", hard: "硬設定", setting: "設定", noneProvided: "暫無", impliedStyle: "遵循大綱所體現的語氣。", noOutline: "未提供大綱；請根據核心構想推演一個克制的場景。", finalRule: "確保每個行動都有因果動機，不與既有事實衝突，並以推動後續情節的方式結尾。只輸出完整章節正文，不要標題或解釋。",
  },
  es: {
    languageName: "Español", role: "Eres un novelista profesional de ficción larga.", create: "Escribe un capítulo nuevo y completo a partir del esquema y el contexto siguientes.", modify: "Revisa el capítulo actual completo según la sugerencia del autor.", rules: "No añadas el título del capítulo. Mantén la continuidad y las reglas fijas del mundo. Devuelve solo la prosa completa.", revisionRule: "Conserva los pasajes eficaces salvo que la sugerencia exija cambiarlos. Aplica la revisión en todo el capítulo y devuelve el capítulo completo, nunca un parche, resumen o explicación.",
    writeIn: "Idioma de escritura", targetLength: "Extensión objetivo", targetUnit: "palabras/caracteres", work: "OBRA", location: "UBICACIÓN ACTUAL", characters: "PERSONAJES", relationships: "RELACIONES", world: "MUNDO Y TRASFONDO", timeline: "CRONOLOGÍA", logic: "CADENAS LÓGICAS", finalCheck: "COMPROBACIÓN FINAL", title: "Título", genre: "Género", premise: "Premisa", styleGuide: "Guía de estilo", referenceExcerpt: "Fragmento de referencia", referenceRule: "imita solo el estilo general; nunca copies frases", volume: "Volumen", volumeSynopsis: "Sinopsis del volumen", chapter: "Capítulo", chapterOutline: "Esquema del capítulo", suggestion: "SUGERENCIA DE REVISIÓN DEL AUTOR", currentDraft: "MANUSCRITO ACTUAL DEL CAPÍTULO", enterSuggestion: "Introduce una sugerencia de revisión concreta", noManuscript: "No se proporcionó el manuscrito actual", unspecified: "Sin especificar", roleUnspecified: "papel sin especificar", personality: "Personalidad", goal: "Objetivo", relatedTo: "relacionado con", hard: "REGLA FIJA", setting: "AMBIENTACIÓN", noneProvided: "No se proporcionó", impliedStyle: "Sigue el tono que sugiere el esquema.", noOutline: "No se proporcionó esquema; deduce una escena contenida a partir de la premisa.", finalRule: "Haz que cada acción tenga una causa clara. No contradigas los hechos establecidos. Termina impulsando la historia. Devuelve solo la prosa completa del capítulo, sin título ni comentarios.",
  },
  de: {
    languageName: "Deutsch", role: "Du bist ein professioneller Autor für lange Romane.", create: "Schreibe anhand der folgenden Gliederung und des Kontexts ein vollständiges neues Kapitel.", modify: "Überarbeite das vollständige aktuelle Kapitel gemäß dem folgenden Vorschlag des Autors.", rules: "Füge keine Kapitelüberschrift hinzu. Bewahre Kontinuität und feste Weltregeln. Gib nur den vollständigen Kapiteltext aus.", revisionRule: "Bewahre gelungene Passagen, sofern der Vorschlag keine Änderung verlangt. Setze die Änderung im gesamten Kapitel um und gib immer das vollständige überarbeitete Kapitel aus, nie einen Patch, eine Zusammenfassung oder eine Erklärung.",
    writeIn: "Schreibsprache", targetLength: "Ziellänge", targetUnit: "Wörter/Zeichen", work: "WERK", location: "AKTUELLE POSITION", characters: "FIGUREN", relationships: "BEZIEHUNGEN", world: "WELT UND HINTERGRUND", timeline: "ZEITLINIE", logic: "LOGIKKETTEN", finalCheck: "ABSCHLUSSPRÜFUNG", title: "Titel", genre: "Genre", premise: "Prämisse", styleGuide: "Stilleitfaden", referenceExcerpt: "Referenzauszug", referenceRule: "nur den übergeordneten Stil nachahmen; niemals Formulierungen kopieren", volume: "Band", volumeSynopsis: "Bandzusammenfassung", chapter: "Kapitel", chapterOutline: "Kapitelgliederung", suggestion: "ÜBERARBEITUNGSVORSCHLAG DES AUTORS", currentDraft: "AKTUELLES KAPITELMANUSKRIPT", enterSuggestion: "Einen konkreten Überarbeitungsvorschlag eingeben", noManuscript: "Kein aktuelles Manuskript vorhanden", unspecified: "Nicht angegeben", roleUnspecified: "Rolle nicht angegeben", personality: "Persönlichkeit", goal: "Ziel", relatedTo: "steht in Beziehung zu", hard: "FESTE REGEL", setting: "SETTING", noneProvided: "Nicht vorhanden", impliedStyle: "Folge dem Ton der Gliederung.", noOutline: "Keine Gliederung vorhanden; leite aus der Prämisse eine zurückhaltende Szene ab.", finalRule: "Begründe jede Handlung kausal. Widersprich keinen etablierten Tatsachen. Beende das Kapitel mit Vorwärtsdrang. Gib nur den vollständigen Kapiteltext ohne Überschrift oder Kommentar aus.",
  },
  fr: {
    languageName: "Français", role: "Vous êtes un romancier professionnel spécialisé dans les récits longs.", create: "Rédigez un nouveau chapitre complet à partir du plan et du contexte ci-dessous.", modify: "Révisez l'intégralité du chapitre actuel selon la suggestion de l'auteur ci-dessous.", rules: "N'ajoutez pas de titre de chapitre. Respectez la continuité et les règles immuables. Retournez uniquement le texte complet du chapitre.", revisionRule: "Conservez les passages réussis sauf si la suggestion exige de les modifier. Appliquez la révision dans tout le chapitre et retournez le chapitre complet, jamais un correctif, un résumé ou une explication.",
    writeIn: "Langue d’écriture", targetLength: "Longueur cible", targetUnit: "mots/caractères", work: "ŒUVRE", location: "EMPLACEMENT ACTUEL", characters: "PERSONNAGES", relationships: "RELATIONS", world: "UNIVERS ET CONTEXTE", timeline: "CHRONOLOGIE", logic: "CHAÎNES LOGIQUES", finalCheck: "VÉRIFICATION FINALE", title: "Titre", genre: "Genre", premise: "Prémisse", styleGuide: "Guide de style", referenceExcerpt: "Extrait de référence", referenceRule: "imiter uniquement le style général, sans jamais copier de formulations", volume: "Tome", volumeSynopsis: "Synopsis du tome", chapter: "Chapitre", chapterOutline: "Plan du chapitre", suggestion: "SUGGESTION DE RÉVISION DE L’AUTEUR", currentDraft: "MANUSCRIT ACTUEL DU CHAPITRE", enterSuggestion: "Saisissez une suggestion de révision précise", noManuscript: "Aucun manuscrit actuel fourni", unspecified: "Non précisé", roleUnspecified: "rôle non précisé", personality: "Personnalité", goal: "Objectif", relatedTo: "lié à", hard: "RÈGLE IMMUABLE", setting: "ÉLÉMENT D’UNIVERS", noneProvided: "Non fourni", impliedStyle: "Suivez le ton suggéré par le plan.", noOutline: "Aucun plan fourni ; déduisez une scène sobre à partir de la prémisse.", finalRule: "Donnez à chaque action une motivation causale. Ne contredisez aucun fait établi. Terminez sur un élan narratif. Retournez uniquement le texte complet du chapitre, sans titre ni commentaire.",
  },
  ja: {
    languageName: "日本語", role: "あなたは長編小説を執筆するプロの作家です。", create: "以下のアウトラインと文脈に基づいて、新しい章を完全な形で執筆してください。", modify: "以下の作者の提案に従って、現在の章全体を改稿してください。", rules: "章タイトルを付けず、連続性と厳格な世界設定を守り、章本文だけを完全な形で出力してください。", revisionRule: "指示で変更が必要な箇所以外の優れた文章は残してください。章全体で問題を解決し、差分・要約・説明ではなく、改稿後の章全文を返してください。",
    writeIn: "執筆言語", targetLength: "目標文字数", targetUnit: "語／文字", work: "作品", location: "現在の位置", characters: "登場人物", relationships: "人物関係", world: "世界観と背景", timeline: "時系列", logic: "論理チェーン", finalCheck: "最終確認", title: "タイトル", genre: "ジャンル", premise: "中核となる構想", styleGuide: "執筆ルール／スタイルガイド", referenceExcerpt: "参考文", referenceRule: "高水準の文体だけを参考にし、表現をコピーしないこと", volume: "巻", volumeSynopsis: "巻のあらすじ", chapter: "章", chapterOutline: "章のアウトライン", suggestion: "作者の修正指示", currentDraft: "現在の章本文", enterSuggestion: "具体的な修正指示を入力してください", noManuscript: "現在の本文は提供されていません", unspecified: "未指定", roleUnspecified: "役割未指定", personality: "性格", goal: "目標", relatedTo: "関係", hard: "厳守設定", setting: "設定", noneProvided: "提供なし", impliedStyle: "アウトラインから読み取れる調子に従ってください。", noOutline: "アウトラインはありません。中核となる構想から抑制の利いた場面を導いてください。", finalRule: "すべての行動に因果的な動機を持たせ、既定の事実と矛盾させないでください。次の展開への勢いを残して終え、章タイトルや解説を付けずに章本文だけを出力してください。",
  },
  pt: {
    languageName: "Português", role: "Você é um romancista profissional de ficção longa.", create: "Escreva um capítulo novo e completo com base no esboço e no contexto abaixo.", modify: "Revise o capítulo atual completo de acordo com a sugestão do autor abaixo.", rules: "Não adicione o título do capítulo. Preserve a continuidade e as regras rígidas do mundo. Retorne apenas a prosa completa.", revisionRule: "Preserve os trechos eficazes, salvo quando a sugestão exigir mudanças. Resolva a questão em todo o capítulo e devolva o capítulo completo, nunca um remendo, resumo ou explicação.",
    writeIn: "Idioma de escrita", targetLength: "Extensão-alvo", targetUnit: "palavras/caracteres", work: "OBRA", location: "LOCALIZAÇÃO ATUAL", characters: "PERSONAGENS", relationships: "RELAÇÕES", world: "MUNDO E CONTEXTO", timeline: "LINHA DO TEMPO", logic: "CADEIAS LÓGICAS", finalCheck: "VERIFICAÇÃO FINAL", title: "Título", genre: "Gênero", premise: "Premissa", styleGuide: "Guia de estilo", referenceExcerpt: "Trecho de referência", referenceRule: "imite apenas o estilo geral; nunca copie frases", volume: "Volume", volumeSynopsis: "Sinopse do volume", chapter: "Capítulo", chapterOutline: "Esboço do capítulo", suggestion: "SUGESTÃO DE REVISÃO DO AUTOR", currentDraft: "MANUSCRITO ATUAL DO CAPÍTULO", enterSuggestion: "Insira uma sugestão de revisão específica", noManuscript: "Nenhum manuscrito atual fornecido", unspecified: "Não especificado", roleUnspecified: "papel não especificado", personality: "Personalidade", goal: "Objetivo", relatedTo: "relacionado a", hard: "REGRA RÍGIDA", setting: "AMBIENTAÇÃO", noneProvided: "Não fornecido", impliedStyle: "Siga o tom sugerido pelo esboço.", noOutline: "Nenhum esboço fornecido; deduza uma cena contida a partir da premissa.", finalRule: "Dê motivação causal a cada ação. Não contradiga fatos estabelecidos. Termine impulsionando a narrativa. Retorne apenas a prosa completa do capítulo, sem título ou comentário.",
  },
  ko: {
    languageName: "한국어", role: "당신은 장편소설을 쓰는 전문 작가입니다.", create: "아래 개요와 맥락을 바탕으로 새로운 장 전체를 작성하세요.", modify: "아래 작가의 수정 제안에 따라 현재 장 전체를 고쳐 쓰세요.", rules: "장 제목을 추가하지 말고, 연속성과 확정 설정을 지키며, 완성된 장 본문만 출력하세요.", revisionRule: "제안에서 변경을 요구하지 않는 좋은 문장은 유지하세요. 장 전체에서 요청한 문제를 해결하고, 수정 조각·요약·설명이 아닌 수정된 장 전문을 반환하세요.",
    writeIn: "집필 언어", targetLength: "목표 분량", targetUnit: "단어/문자", work: "작품", location: "현재 위치", characters: "등장인물", relationships: "인물 관계", world: "세계관과 배경", timeline: "시간선", logic: "논리 체인", finalCheck: "최종 점검", title: "제목", genre: "장르", premise: "핵심 구상", styleGuide: "집필 규칙／스타일 가이드", referenceExcerpt: "참고문", referenceRule: "상위 수준의 문체만 참고하고 문구를 복사하지 말 것", volume: "권", volumeSynopsis: "권 소개", chapter: "장", chapterOutline: "장 개요", suggestion: "작가의 수정 제안", currentDraft: "현재 장 원고", enterSuggestion: "구체적인 수정 제안을 입력하세요", noManuscript: "현재 원고가 제공되지 않았습니다", unspecified: "미지정", roleUnspecified: "역할 미지정", personality: "성격", goal: "목표", relatedTo: "관련", hard: "확정 설정", setting: "설정", noneProvided: "제공 없음", impliedStyle: "개요에서 드러나는 어조를 따르세요.", noOutline: "개요가 없습니다. 핵심 구상에서 절제된 장면을 추론하세요.", finalRule: "모든 행동에 인과적 동기를 부여하고 기존 사실과 모순되지 않게 하세요. 다음 전개를 이끄는 힘을 남기며 끝내고, 장 제목이나 해설 없이 완성된 본문만 출력하세요.",
  },
};

export function buildChapterPrompt({ work, volume, chapter, bundle, mode, suggestion = "" }: { work: PromptWork; volume?: PromptVolume; chapter: PromptChapter; bundle: PromptBundle; mode: ChapterPromptMode; suggestion?: string }) {
  const language = localePrompts[normalizeWritingLanguage(work.language)];
  const names = new Map(bundle.characters.map((item) => [item.id, item.name]));
  const charactersText = bundle.characters.map((item) => `- ${item.name} (${item.role || language.roleUnspecified}): ${item.description || ""}\n  ${language.personality}: ${item.personality || ""}\n  ${language.goal}: ${item.goal || ""}`).join("\n") || `- ${language.noneProvided}`;
  const relationshipsText = bundle.relationships.map((item) => `- ${names.get(item.sourceCharacterId) || item.sourceCharacterId} —${item.relationship || language.relatedTo}→ ${names.get(item.targetCharacterId) || item.targetCharacterId}: ${item.description || ""}`).join("\n") || `- ${language.noneProvided}`;
  const worldText = bundle.world.map((item) => `- [${item.isHardSetting ? language.hard : item.category || language.setting}] ${item.title}: ${item.content || ""}`).join("\n") || `- ${language.noneProvided}`;
  const timelineText = bundle.timeline.map((item) => `- ${item.timeLabel || item.position} · ${item.title}: ${item.content || ""}`).join("\n") || `- ${language.noneProvided}`;
  const logicText = bundle.logicLinks.map((item) => `- ${item.fromRef} —${item.relation}→ ${item.toRef}: ${item.notes || ""}`).join("\n") || `- ${language.noneProvided}`;
  const revisionSection = mode === "modify" ? `\n\n# ${language.suggestion}\n${suggestion.trim() || `[${language.enterSuggestion}]`}\n\n${language.revisionRule}\n\n# ${language.currentDraft}\n${chapter.content?.trim() || `[${language.noManuscript}]`}` : "";
  return `${language.role}\n\n${mode === "modify" ? language.modify : language.create}\n${language.rules}\n${language.writeIn}: ${language.languageName}\n${language.targetLength}: ${chapter.targetWords} ${language.targetUnit}.\n\n# ${language.work}\n${language.title}: ${work.title}\n${language.genre}: ${work.genre || language.unspecified}\n${language.premise}: ${work.premise || work.description || ""}\n${language.styleGuide}: ${work.styleGuide || language.impliedStyle}\n${language.referenceExcerpt} (${language.referenceRule}):\n${work.referenceExcerpt || language.noneProvided}\n\n# ${language.location}\n${language.volume} ${volume?.position ?? "?"}: ${volume?.title ?? ""}\n${language.volumeSynopsis}: ${volume?.synopsis ?? ""}\n${language.chapter} ${chapter.position}: ${chapter.title}\n${language.chapterOutline}:\n${chapter.outline || language.noOutline}${revisionSection}\n\n# ${language.characters}\n${charactersText}\n\n# ${language.relationships}\n${relationshipsText}\n\n# ${language.world}\n${worldText}\n\n# ${language.timeline}\n${timelineText}\n\n# ${language.logic}\n${logicText}\n\n# ${language.finalCheck}\n${language.finalRule}`;
}
