export const supportedLocales = [
  { code: "en", label: "English" },
  { code: "zh-CN", label: "简体中文" },
  { code: "zh-TW", label: "繁體中文" },
  { code: "es", label: "Español" },
  { code: "de", label: "Deutsch" },
  { code: "fr", label: "Français" },
  { code: "ja", label: "日本語" },
  { code: "pt", label: "Português" },
  { code: "ko", label: "한국어" },
] as const;

export type UiLocale = (typeof supportedLocales)[number]["code"];
export type TranslationVars = Record<string, string | number>;
export const defaultLocale: UiLocale = "en";

export function resolveLocale(value?: string | null): UiLocale {
  return supportedLocales.some((item) => item.code === value) ? value as UiLocale : defaultLocale;
}

const en: Record<string, string> = {
  "language.label": "Interface language",
  "nav.features": "Features", "nav.library": "Library", "nav.about": "About & disclaimer",
  "auth.login": "Log in", "auth.logout": "Log out", "auth.start": "Start writing",
  "footer.tagline": "Leave structure to the tool and choices to the author.", "footer.product": "Product",
  "footer.studio": "Writing studio", "footer.library": "Community library", "footer.notes": "Information",
  "footer.disclaimer": "Disclaimer", "footer.privacy": "Privacy & content responsibility", "footer.important": "Important",
  "footer.boundary": "This site only manages stories, organizes prompts, and provides MCP access. It does not provide or resell any AI model service.",
  "home.metaTitle": "Story Studio Cloud — Free AI-assisted novel workspace",
  "home.eyebrow": "Your model, your story", "home.headline": "Turn scattered ideas", "home.headlineEm": "into a complete book.",
  "home.lede": "A calm writing workspace for outlines, character relationships, worldbuilding, logic chains, and chapter versions. Copy complete prompts into any language model, or let your own Codex collaborate through MCP.",
  "home.enter": "Enter my studio", "home.chatgpt": "Log in with ChatGPT", "home.explore": "Explore the library",
  "home.microcopy": "Free management tool · No bundled model credits · Private by default",
  "home.saved": "Saved", "home.demoVolume1": "Volume I · Tide Line", "home.demoChapter1": "01  Lost & Found",
  "home.demoChapter2": "02  The Clock Against the Current", "home.demoChapter3": "03  The Nameless Route", "home.demoVolume2": "Volume II · City of Mist",
  "home.demoTitle": "Lost & Found", "home.demoP1": "Rain slipped down the iron bones of the platform like a letter years too late.",
  "home.demoP2": "Mara stopped beneath the fourth lamp. The suitcase without a shadow was quietly tapping its own lock.",
  "home.step1Title": "Build the skeleton", "home.step1Body": "Keep volumes, chapters, and target lengths clear",
  "home.step2Title": "Add story memory", "home.step2Body": "Bring in characters, settings, and timelines as needed",
  "home.step3Title": "Hand it to AI", "home.step3Body": "You decide which model receives the complete prompt",
  "home.workflowKicker": "A calmer way to write", "home.workflowTitle": "AI can be powerful. Your writing process can stay clear.",
  "home.workflowBody": "We organize the context. Your model, credits, manuscript, and publishing decisions remain yours.",
  "home.feature1Title": "A story tree, not a file pile", "home.feature1Body": "Expand or collapse volumes and chapters, and mark exactly which chapters need revision after an outline changes.",
  "home.feature2Title": "Bounded context", "home.feature2Body": "Compose only the relevant characters, relationships, scenes, timeline, and logic chains for each chapter.",
  "home.feature3Title": "Works with any model", "home.feature3Body": "Copy prompts to ChatGPT, Gemini, or a local model, or expose MCP so your own Codex can read and write drafts.",
  "home.treeVolume": "⌄ Volume I  Wind from the Old World", "home.tree1": "├ 01  The Train Through Sunset", "home.tree2": "├ 02  The Forgotten Station  Update needed", "home.tree3": "└ 03  The Blue Suitcase",
  "home.tagCharacters": "Characters 4", "home.tagRelations": "Relationships 6", "home.tagRules": "Hard rules 3", "home.tagSummary": "Previous summary",
  "home.libraryKicker": "Community bookshelf", "home.libraryTitle": "Stories friends choose to share can meet here.", "home.browse": "Browse all works →",
  "home.noDescription": "The author has not added a description yet.", "home.read": "Start reading →",
  "home.ctaKicker": "Your story, your tools", "home.ctaTitle": "The next chapter starts with a clear idea.",
  "home.ctaBody": "No platform model bill and no locked format. Create your first work for free.", "home.ctaButton": "Open the writing studio",
  "about.kicker": "About & disclaimer", "about.title": "This is a writing desk, not the author.",
  "about.intro": "Story Studio Cloud is a non-commercial story-architecture and manuscript-management tool. We want friends to choose their own AI, retain their data, and understand the boundaries of AI-assisted writing.",
  "about.toolTitle": "What the tool does", "about.toolBody": "The site manages outlines, chapters, characters, relationships, worldbuilding, timelines, logic chains, prompts, imports and exports, public reading, and MCP access. It does not provide, resell, or broker any language-model service, nor does it pay for ChatGPT, Codex, Gemini, local models, or other third-party services.",
  "about.contentTitle": "Content responsibility", "about.contentBody": "Users are responsible for content they upload, generate, edit, and publish, including accuracy, copyright, trademarks, privacy, reputation, and applicable law. AI output may contain errors, bias, repetition, fabrication, or similarities to other works; authors should review it before publishing.",
  "about.warrantyTitle": "No warranty", "about.warrantyBody": "The site does not guarantee the quality, continuity, originality, publishability, or commercial outcome of AI-generated content and does not provide legal, publishing, medical, investment, or other professional advice. The service is provided as is and may be temporarily unavailable during testing, maintenance, or hosting limits.",
  "about.privacyTitle": "Privacy and default visibility", "about.private1": "Works are visible only to their author by default.",
  "about.private2": "Only works and chapters the author explicitly publishes appear in the community library.", "about.private3": "Users copy prompts to external models themselves; the site does not send them in the background.",
  "about.private4": "MCP access tokens are shown once and can be revoked at any time. Do not share them.", "about.reportTitle": "Reports and takedowns",
  "about.reportBody": "If a public work infringes your rights, provide its link, an explanation of your rights, and verifiable contact information. A dedicated contact address will be added before wider release; after a reasonable notice, we may temporarily hide the content and contact its publisher.",
  "library.kicker": "Community bookshelf", "library.title": "Community Library", "library.intro": "Only works authors explicitly publish appear here. Reading does not require login; writing and publishing require an author account.",
  "library.emptyTitle": "The shelves are still quiet", "library.emptyBody": "The first public stories from friends will appear here. Sign in to the studio and you can be among the first authors.",
  "library.noDescription": "The author has not added a description yet.", "library.read": "Read work →",
  "reader.noDescription": "The author has not added a description yet.", "reader.empty": "The author has not published any chapters yet.",
  "studio.navWorks": "Works", "studio.navConnections": "Connections", "studio.navLibrary": "Library", "studio.privateSpace": "Private writing space", "studio.privateDefault": "Private by default",
  "dashboard.kicker": "MY MANUSCRIPTS", "dashboard.morning": "Good morning", "dashboard.afternoon": "Good afternoon", "dashboard.evening": "Good evening",
  "dashboard.intro": "Each work is an independent space. Only you can see it by default.", "dashboard.import": "⇩ Import full backup", "dashboard.importing": "Importing…", "dashboard.new": "＋ New work",
  "dashboard.works": "Works", "dashboard.chapters": "Chapters", "dashboard.words": "Total words", "dashboard.published": "Published",
  "dashboard.publicWork": "Published work", "dashboard.privateDraft": "Private draft", "dashboard.deleteTitle": "Delete work",
  "dashboard.noDescription": "No description yet. Open the studio to continue.", "dashboard.chapterUnit": "chapters", "dashboard.wordUnit": "words", "dashboard.continue": "Continue writing →",
  "dashboard.emptyTitle": "Your first story starts here", "dashboard.emptyBody": "Give it a name. We will prepare the first volume and chapter, then you can add characters, worldbuilding, and logic chains.", "dashboard.emptyButton": "Create my first work",
  "dashboard.newTitle": "Create a new work", "dashboard.newIntro": "This creates a blank structure and does not call any AI.", "dashboard.workTitle": "Title", "dashboard.titlePlaceholder": "For example: South of the Storm",
  "dashboard.genre": "Genre", "dashboard.genrePlaceholder": "Fantasy / Mystery / Romance", "dashboard.writingLanguage": "Writing language", "dashboard.premise": "One-sentence premise", "dashboard.premisePlaceholder": "Who is the protagonist, what do they want, and what is the main obstacle?",
  "common.close": "Close", "common.cancel": "Cancel", "common.add": "Add", "common.save": "Save", "common.delete": "Delete", "common.none": "None",
  "dashboard.creating": "Creating…", "dashboard.createOpen": "Create and open", "dashboard.createFailed": "Could not create the work", "dashboard.importFailed": "Could not import the backup",
  "dashboard.deleteQuestion": "Delete “{title}”?", "dashboard.deleteBody": "The outline, characters, settings, and all manuscript text will be permanently deleted. Its public reading page will disappear immediately. No full backup is kept automatically.", "dashboard.keep": "Keep work", "dashboard.deletePermanent": "Delete permanently",
  "connections.kicker": "CONNECTIONS", "connections.title": "Connect your own AI", "connections.intro": "The site does not provide a model. Copy a prompt, or let your own Codex read and write drafts through MCP.",
  "connections.external": "External models", "connections.externalBody": "In the chapter editor, click “Build AI prompt from outline,” then paste it into ChatGPT, Gemini, or a local model. Paste the result back into the manuscript and save.",
  "connections.noKey": "No API key required", "connections.noCredits": "Uses no model credits from this site", "connections.anyModel": "Works with any long-context model",
  "connections.codex": "Codex connection", "connections.codexBody": "A token lets your own Codex inspect story structure, read context, and save chapter drafts. It uses the reader’s own Codex allowance.",
  "connections.tokens": "Access tokens", "connections.tokensBody": "A token is shown only once after creation. It is a key to your studio; do not give it to anyone.",
  "connections.tokenName": "Token name", "connections.tokenPlaceholder": "For example: Codex on my home computer", "connections.creating": "Creating…", "connections.create": "Create token",
  "connections.copyNow": "Copy and store this securely now", "connections.copy": "Copy token", "connections.revoked": "Revoked", "connections.lastUsed": "Last used {date}", "connections.neverUsed": "Never used", "connections.revoke": "Revoke", "connections.empty": "No tokens have been created.",
  "connections.what": "What can Codex do?", "connections.readStructure": "Read story structure", "connections.readStructureBody": "List volumes, chapters, outlines, and revisions",
  "connections.readContext": "Read relevant context", "connections.readContextBody": "Characters, relationships, worldbuilding, timeline, and logic chains",
  "connections.saveDrafts": "Save chapter drafts", "connections.saveDraftsBody": "Write with revision checks so recent edits are not overwritten",
  "connections.safety": "Safety boundary: MCP cannot delete works or publish chapters automatically. Publishing always happens in the web studio.",
  "work.myWorks": "My works", "work.public": "Published", "work.private": "Private draft", "work.saving": "Saving…", "work.saved": "Saved", "work.saveFailed": "Save failed",
  "work.backup": "Full backup ⇧", "work.settings": "Work settings", "work.readPage": "Reading page ↗", "work.saveChapter": "Save chapter",
  "work.manuscript": "MANUSCRIPT", "work.outline": "Story outline", "work.addVolume": "Add volume", "work.addChapter": "Add chapter", "work.volume": "Volume {number}", "work.notStarted": "Not started", "work.chapterPublished": "Published", "work.volumes": "volumes",
  "work.targetWords": "Target length", "work.chapterTitle": "Chapter title", "work.chapterOutline": "Chapter outline", "work.outlinePlaceholder": "What happens in this chapter? What are the character’s goal, obstacle, and ending hook?",
  "work.aiPrompt": "✦ Build AI prompt from outline", "work.publishChapter": "Publish this chapter", "work.body": "Chapter manuscript", "work.bodyPlaceholder": "Start writing here…\n\nOr use the button above, copy the complete prompt into your own AI, and paste the result back here.", "work.addFirst": "Add a chapter first.",
  "work.context": "AI context for this chapter", "work.contextAuto": "Automatically included in the prompt", "work.manage": "Manage", "work.characters": "Characters", "work.settingsTab": "World", "work.time": "Timeline", "work.logic": "Logic",
  "work.privacyTitle": "Privacy note", "work.privacyBody": "This context is assembled into a prompt in your browser. The site does not send it unless you copy it to an external model.",
  "work.promptTitle": "Copy to your own model", "work.promptBody": "The prompt includes the work foundation, chapter outline, characters, relationships, hard settings, timeline, and logic chains.", "work.promptPrivacy": "The site does not send this text or consume any model credits.", "work.copyPrompt": "Copy complete prompt",
  "work.newVolume": "NEW VOLUME", "work.newChapter": "NEW CHAPTER", "work.addOneVolume": "Add a volume", "work.addOneChapter": "Add a chapter", "work.title": "Title", "work.volumeTitlePlaceholder": "Name of this volume", "work.chapterTitlePlaceholder": "Name of this chapter", "work.volumeSynopsis": "Volume synopsis", "work.goalConflict": "Goals, conflict, key changes, and ending hook",
  "work.settingsKicker": "WORK SETTINGS", "work.foundation": "Story foundation & publishing", "work.genre": "Genre", "work.language": "Writing language", "work.description": "Description", "work.premise": "Core premise", "work.style": "Writing rules / style guide", "work.reference": "Reference excerpt",
  "work.publishPage": "Publish work page", "work.publishPageBody": "Readers only see chapters that also have “Publish this chapter” selected.", "work.saveSettings": "Save settings",
  "memory.title": "Manage characters and story memory", "memory.intro": "These details enter every chapter’s AI prompt. Keep them clear and consistent.", "memory.character": "Characters", "memory.relationship": "Relationships", "memory.world": "Worldbuilding", "memory.timeline": "Timeline", "memory.logic": "Logic chains",
  "memory.emptyCategory": "No entries in this category.", "memory.edit": "Edit entry", "memory.add": "Add entry", "memory.cancelEdit": "Cancel editing", "memory.saveEdit": "Save changes", "memory.saveFailed": "Could not save",
  "memory.name": "Name", "memory.role": "Story role", "memory.rolePlaceholder": "Protagonist / Rival / Mentor", "memory.description": "Description", "memory.personality": "Personality", "memory.goal": "Current goal",
  "memory.source": "Source character", "memory.select": "Select", "memory.target": "Target character", "memory.selectTarget": "Select target character", "memory.relationshipType": "Relationship type", "memory.relationshipPlaceholder": "Parent / Ally / Rival / Secret love", "memory.relationshipNotes": "Relationship notes",
  "memory.entryName": "Name", "memory.category": "Category", "memory.categoryPlaceholder": "Place / Rule / Organization", "memory.details": "Detailed setting", "memory.hard": "Hard setting (AI must not violate it)",
  "memory.order": "Order", "memory.storyTime": "Story time", "memory.timePlaceholder": "Three years ago / Day seven", "memory.eventName": "Event name", "memory.eventDetails": "Event details",
  "memory.cause": "Cause / premise", "memory.relation": "Logical relation", "memory.relationPlaceholder": "Causes / Depends on / Reveals", "memory.result": "Result / payoff", "memory.notes": "Notes",
  "memory.personFallback": "Character", "memory.noDescription": "No description", "memory.noCharacters": "No characters yet. Click Manage to add one.", "memory.noWorld": "No worldbuilding entries yet.", "memory.noTimeline": "No timeline events yet.", "memory.noLogic": "No logic chains yet.", "memory.hardBadge": "Hard", "memory.orderValue": "Order {number}"
};

const zhCN: Record<string, string> = {
  "language.label":"界面语言","nav.features":"功能","nav.library":"小说广场","nav.about":"关于与免责","auth.login":"登录","auth.logout":"退出","auth.start":"开始写作",
  "footer.tagline":"把结构留给工具，把选择留给作者。","footer.product":"产品","footer.studio":"写作工作台","footer.library":"小说广场","footer.notes":"说明","footer.disclaimer":"免责声明","footer.privacy":"隐私与内容责任","footer.important":"重要说明","footer.boundary":"本站只提供作品管理、提示词整理和 MCP 读写能力，不提供或转售任何 AI 模型服务。",
  "home.eyebrow":"模型归你，故事也归你","home.headline":"把散落的灵感，","home.headlineEm":"长成一本书。","home.lede":"一处安静的写作工作台，替你管理大纲、人物关系、世界观、逻辑链和章节版本。复制完整提示词到任意大模型，也可以让你自己的 Codex 通过 MCP 协助创作。","home.enter":"进入我的工作台","home.chatgpt":"使用 ChatGPT 登录","home.explore":"先逛逛小说广场","home.microcopy":"免费管理工具 · 不代购模型额度 · 作品默认私密","home.saved":"已保存",
  "home.demoVolume1":"第一卷 · 潮汐线","home.demoChapter1":"01  失物招领处","home.demoChapter2":"02  逆流的钟","home.demoChapter3":"03  无名航路","home.demoVolume2":"第二卷 · 雾之城","home.demoTitle":"失物招领处","home.demoP1":"雨水沿着站台的铁骨落下，像一封迟到了很多年的信。","home.demoP2":"周眠在第四盏灯下停住。那只没有影子的行李箱，正轻轻敲着自己的锁。",
  "home.step1Title":"先搭骨架","home.step1Body":"卷、章和建议字数清楚排好","home.step2Title":"再补记忆","home.step2Body":"人物、设定、时间线随章节取用","home.step3Title":"最后交给 AI","home.step3Body":"完整提示词由你决定发给谁","home.workflowTitle":"AI 可以很强，写作流程不必很乱。","home.workflowBody":"我们只负责把上下文整理好。你的模型、额度、原稿和发布决定，始终由你掌握。","home.feature1Title":"故事树，而不是文件堆","home.feature1Body":"卷和章可以展开收起；大纲变化时，准确标记哪些章节需要重写。","home.feature2Title":"上下文有边界","home.feature2Body":"按章节组合人物、关系、场景、时间线和逻辑链，不必把整本书反复塞给模型。","home.feature3Title":"任何模型都能接","home.feature3Body":"复制提示词到 ChatGPT、Gemini 或本地模型；也可以开放 MCP，让你自己的 Codex 读写草稿。","home.treeVolume":"⌄ 第一卷  风从旧世界来","home.tree1":"├ 01  火车穿过落日","home.tree2":"├ 02  无人记得的车站  需更新","home.tree3":"└ 03  蓝色行李箱","home.tagCharacters":"人物 4","home.tagRelations":"关系 6","home.tagRules":"硬设定 3","home.tagSummary":"前文摘要","home.libraryTitle":"朋友愿意公开的故事，会在这里相遇。","home.browse":"浏览全部作品 →","home.noDescription":"作者还没有填写作品简介。","home.read":"开始阅读 →","home.ctaTitle":"下一章，从一个清楚的念头开始。","home.ctaBody":"没有平台模型账单，也没有被锁住的格式。先免费建立你的第一部作品。","home.ctaButton":"打开写作工作台",
  "about.title":"这是一张写作桌，不是内容的作者。","about.intro":"Story Studio Cloud 是非商业的作品架构与文稿管理工具。我们希望朋友们能自由选择自己的 AI、保留自己的数据，并清楚理解 AI 辅助创作的边界。","about.toolTitle":"工具定位","about.toolBody":"本站提供大纲、章节、人物、关系、世界观、时间线、逻辑链、提示词整理、导入导出、公开阅读及 MCP 读写等管理能力。本站本身不提供、转售或代理任何大语言模型服务，也不会替用户承担 ChatGPT、Codex、Gemini、本地模型或其他第三方服务的费用。","about.contentTitle":"内容责任","about.contentBody":"用户应当对自己上传、生成、编辑和发布的内容负责，包括事实准确性、版权、商标、隐私、名誉及适用法律。AI 输出可能存在错误、偏见、重复、虚构或与他人作品相似的内容；发布前应由作者本人检查。","about.warrantyTitle":"不作保证","about.warrantyBody":"本站不保证 AI 生成内容的质量、连贯性、原创性、可出版性或商业结果，也不构成法律、出版、医疗、投资或其他专业建议。服务按现状提供，可能因测试、维护或托管限制而暂时不可用。","about.privacyTitle":"隐私与默认可见性","about.private1":"作品默认仅作者本人可见。","about.private2":"只有作者主动发布的作品和章节才会出现在小说广场。","about.private3":"外部模型提示词由用户主动复制；本站不会在后台替用户发送。","about.private4":"MCP 访问令牌只在创建时显示一次，可随时撤销；请勿分享给他人。","about.reportTitle":"举报与下架","about.reportBody":"若公开作品侵犯你的合法权益，请提供作品链接、权利说明和可核验的联系方式。项目正式公开前会补充专用联系邮箱；收到合理通知后，我们可以临时隐藏相关内容并联系发布者核实。",
  "library.title":"小说广场","library.intro":"这里仅展示作者主动公开的作品。阅读不需要登录；创作和发布需要作者登录。","library.emptyTitle":"书架还很安静","library.emptyBody":"第一批朋友的公开作品会出现在这里。登录工作台，你也可以成为第一位作者。","library.noDescription":"作者还没有填写简介。","library.read":"阅读作品 →","reader.noDescription":"作者还没有填写简介。","reader.empty":"作者尚未发布章节。",
  "studio.navWorks":"作品","studio.navConnections":"连接","studio.navLibrary":"广场","studio.privateSpace":"私人写作空间","studio.privateDefault":"默认私密","dashboard.morning":"早上好","dashboard.afternoon":"下午好","dashboard.evening":"晚上好","dashboard.intro":"每一部作品都是独立空间。它们默认只有你能看到。","dashboard.import":"⇩ 导入本地完整备份","dashboard.importing":"正在导入…","dashboard.new":"＋ 新建作品","dashboard.works":"作品","dashboard.chapters":"章节","dashboard.words":"累计字数","dashboard.published":"已公开","dashboard.publicWork":"公开作品","dashboard.privateDraft":"私人草稿","dashboard.deleteTitle":"删除作品","dashboard.noDescription":"还没有作品简介。打开工作台继续完善。","dashboard.chapterUnit":"章","dashboard.wordUnit":"字","dashboard.continue":"继续写作 →","dashboard.emptyTitle":"你的第一部作品，从这里开始","dashboard.emptyBody":"先建立一个名字。系统会替你准备第一卷和第一章，之后再逐步添加人物、世界观和逻辑线。","dashboard.emptyButton":"建立第一部作品","dashboard.newTitle":"建立新作品","dashboard.newIntro":"这里只建立空白结构，不会调用任何 AI。","dashboard.workTitle":"作品名","dashboard.titlePlaceholder":"例如：风暴以南","dashboard.genre":"类型","dashboard.writingLanguage":"写作语言","dashboard.premise":"一句话构想","dashboard.premisePlaceholder":"主角是谁，他想要什么，最大的阻碍是什么？","common.close":"关闭","common.cancel":"取消","common.add":"添加","common.save":"保存","common.delete":"删除","dashboard.creating":"正在建立…","dashboard.createOpen":"建立并打开","dashboard.createFailed":"创建失败","dashboard.importFailed":"导入失败","dashboard.deleteQuestion":"删除《{title}》？","dashboard.deleteBody":"大纲、人物、设定和全部正文都会永久删除，公开阅读页也会立即消失。完整备份不会自动保留。","dashboard.keep":"保留作品","dashboard.deletePermanent":"确认永久删除",
  "connections.title":"连接你自己的 AI","connections.intro":"站点不提供模型。你可以复制提示词，或允许自己的 Codex 通过 MCP 读写草稿。","connections.external":"外部模型","connections.externalBody":"在章节编辑器点击“按大纲生成 AI 提示词”，再粘贴到 ChatGPT、Gemini 或本地模型。结果直接贴回正文并保存。","connections.noKey":"不需要 API Key","connections.noCredits":"不会从本站扣除模型额度","connections.anyModel":"适合任何支持长文本的模型","connections.codex":"Codex 连接","connections.codexBody":"令牌让你自己的 Codex 查看作品结构、读取上下文和保存章节草稿。消耗的是使用者自己的 Codex 额度。","connections.tokens":"访问令牌","connections.tokensBody":"令牌只在创建后显示一次。它等同于工作台钥匙，请勿发给别人。","connections.tokenPlaceholder":"例如：家里电脑的 Codex","connections.creating":"正在创建…","connections.create":"生成新令牌","connections.copyNow":"请现在复制并安全保存","connections.copy":"复制令牌","connections.revoked":"已撤销","connections.lastUsed":"最近使用 {date}","connections.neverUsed":"尚未使用","connections.revoke":"撤销","connections.empty":"尚未创建令牌。","connections.what":"Codex 能做什么？","connections.readStructure":"读取作品结构","connections.readStructureBody":"列出卷、章、大纲与版本号","connections.readContext":"读取相关上下文","connections.readContextBody":"人物、关系、世界观、时间线和逻辑链","connections.saveDrafts":"保存章节草稿","connections.saveDraftsBody":"带版本检查写回，避免覆盖你刚做的修改","connections.safety":"安全边界：MCP 不能删除作品，也不能自动公开章节。发布始终要在网页工作台完成。",
  "work.myWorks":"我的作品","work.public":"已公开","work.private":"私人草稿","work.saving":"正在保存…","work.saved":"已保存","work.saveFailed":"保存失败","work.backup":"完整备份 ⇧","work.settings":"作品设置","work.readPage":"阅读页 ↗","work.saveChapter":"保存章节","work.outline":"故事大纲","work.addVolume":"添加卷","work.addChapter":"添加章节","work.volume":"第 {number} 卷","work.notStarted":"未开始","work.chapterPublished":"已发布","work.volumes":"卷","work.targetWords":"建议字数","work.chapterTitle":"章节标题","work.chapterOutline":"章节大纲","work.outlinePlaceholder":"这一章发生什么？人物的目标、阻碍和结尾钩子是什么？","work.aiPrompt":"✦ 按大纲生成 AI 提示词","work.publishChapter":"发布本章","work.body":"章节正文","work.bodyPlaceholder":"从这里开始写故事……\n\n你也可以点击上方按钮，把完整提示词复制到自己的 AI，然后将结果贴回这里。","work.addFirst":"请先添加一个章节。","work.context":"本章 AI 上下文","work.contextAuto":"生成提示词时自动带入","work.manage":"管理","work.characters":"人物","work.settingsTab":"设定","work.time":"时间","work.logic":"逻辑","work.privacyTitle":"隐私提示","work.privacyBody":"这些内容只在浏览器中组成提示词。除非你主动复制给外部模型，否则本站不会发送。","work.promptTitle":"复制到你自己的模型","work.promptBody":"提示词已包含作品基石、本章大纲、人物、关系、硬设定、时间线和逻辑链。","work.promptPrivacy":"本站不会发送这段内容，也不会消耗任何模型额度。","work.copyPrompt":"复制完整提示词","work.addOneVolume":"添加一卷","work.addOneChapter":"添加一章","work.title":"标题","work.volumeTitlePlaceholder":"这一卷的名字","work.chapterTitlePlaceholder":"这一章的名字","work.volumeSynopsis":"本卷介绍","work.goalConflict":"目标、冲突、关键变化与结尾钩子","work.foundation":"作品基石与发布","work.genre":"类型","work.language":"写作语言","work.description":"简介","work.premise":"核心构想","work.style":"写作规则 / 风格指南","work.reference":"参考范本","work.publishPage":"公开作品主页","work.publishPageBody":"只有同时勾选“发布本章”的章节才会让读者看到。","work.saveSettings":"保存设置",
  "memory.title":"管理人物与故事设定","memory.intro":"这些资料会进入每一章的 AI 提示词，请尽量写清楚、保持稳定。","memory.character":"人物","memory.relationship":"关系","memory.world":"世界观","memory.timeline":"时间线","memory.logic":"逻辑链","memory.emptyCategory":"这个分类还没有资料。","memory.edit":"修改条目","memory.add":"添加条目","memory.cancelEdit":"取消修改","memory.saveEdit":"保存修改","memory.saveFailed":"保存失败","memory.name":"姓名","memory.role":"角色定位","memory.rolePlaceholder":"主角 / 对手 / 导师","memory.description":"人物描述","memory.personality":"个性","memory.goal":"当前目标","memory.source":"起点人物","memory.select":"请选择","memory.target":"终点人物","memory.selectTarget":"请选择终点人物","memory.relationshipType":"关系类型","memory.relationshipPlaceholder":"父子 / 同盟 / 敌对 / 暗恋","memory.relationshipNotes":"关系说明","memory.entryName":"名称","memory.category":"分类","memory.categoryPlaceholder":"地点 / 规则 / 组织","memory.details":"详细设定","memory.hard":"硬设定（AI 不得违反）","memory.order":"顺序","memory.storyTime":"故事时间","memory.timePlaceholder":"三年前 / 第七日","memory.eventName":"事件名","memory.eventDetails":"事件说明","memory.cause":"起因 / 前提","memory.relation":"逻辑关系","memory.relationPlaceholder":"导致 / 依赖 / 揭示","memory.result":"结果 / 回收","memory.notes":"说明","memory.personFallback":"人物","memory.noDescription":"暂无描述","memory.noCharacters":"还没有人物。点击上方“管理”添加。","memory.noWorld":"还没有世界观设定。","memory.noTimeline":"还没有时间线事件。","memory.noLogic":"还没有逻辑链。","memory.hardBadge":"硬设定","memory.orderValue":"顺序 {number}"
};

const overrides: Partial<Record<UiLocale, Record<string, string>>> = {
  "zh-CN": zhCN,
  "zh-TW": { ...zhCN, "language.label":"介面語言", "nav.features":"功能", "nav.library":"小說廣場", "nav.about":"關於與免責", "auth.login":"登入", "auth.logout":"登出", "auth.start":"開始寫作", "studio.privateSpace":"私人寫作空間", "studio.privateDefault":"預設私密", "dashboard.new":"＋ 新增作品", "dashboard.writingLanguage":"寫作語言", "common.cancel":"取消", "common.save":"儲存", "work.saved":"已儲存", "work.saving":"正在儲存…", "work.saveChapter":"儲存章節", "memory.character":"人物", "memory.relationship":"關係", "memory.world":"世界觀", "memory.timeline":"時間線", "memory.logic":"邏輯鏈" },
  es: { "language.label":"Idioma de la interfaz","nav.features":"Funciones","nav.library":"Biblioteca","nav.about":"Acerca de y aviso legal","auth.login":"Iniciar sesión","auth.logout":"Cerrar sesión","auth.start":"Empezar a escribir","studio.navWorks":"Obras","studio.navConnections":"Conexiones","studio.navLibrary":"Biblioteca","studio.privateSpace":"Espacio privado de escritura","studio.privateDefault":"Privado por defecto","dashboard.morning":"Buenos días","dashboard.afternoon":"Buenas tardes","dashboard.evening":"Buenas noches","dashboard.intro":"Cada obra es un espacio independiente. Solo tú puedes verla por defecto.","dashboard.import":"⇩ Importar copia completa","dashboard.new":"＋ Nueva obra","dashboard.works":"Obras","dashboard.chapters":"Capítulos","dashboard.words":"Palabras totales","dashboard.published":"Publicadas","dashboard.newTitle":"Crear una obra","dashboard.workTitle":"Título","dashboard.genre":"Género","dashboard.writingLanguage":"Idioma de escritura","common.cancel":"Cancelar","common.add":"Añadir","common.save":"Guardar","common.delete":"Eliminar","connections.title":"Conecta tu propia IA","work.myWorks":"Mis obras","work.settings":"Ajustes de la obra","work.saveChapter":"Guardar capítulo","work.outline":"Esquema de la historia","work.addVolume":"Añadir volumen","work.addChapter":"Añadir capítulo","work.aiPrompt":"✦ Crear prompt de IA desde el esquema","work.context":"Contexto de IA de este capítulo","work.manage":"Gestionar","work.characters":"Personajes","work.settingsTab":"Mundo","work.time":"Cronología","work.logic":"Lógica","memory.title":"Gestionar personajes y memoria de la historia","memory.character":"Personajes","memory.relationship":"Relaciones","memory.world":"Mundo","memory.timeline":"Cronología","memory.logic":"Cadenas lógicas" },
  de: { "language.label":"Oberflächensprache","nav.features":"Funktionen","nav.library":"Bibliothek","nav.about":"Über uns & Haftung","auth.login":"Anmelden","auth.logout":"Abmelden","auth.start":"Schreiben","studio.navWorks":"Werke","studio.navConnections":"Verbindungen","studio.navLibrary":"Bibliothek","studio.privateSpace":"Privater Schreibbereich","studio.privateDefault":"Standardmäßig privat","dashboard.morning":"Guten Morgen","dashboard.afternoon":"Guten Tag","dashboard.evening":"Guten Abend","dashboard.intro":"Jedes Werk ist ein eigener Bereich und standardmäßig nur für dich sichtbar.","dashboard.import":"⇩ Vollständige Sicherung importieren","dashboard.new":"＋ Neues Werk","dashboard.works":"Werke","dashboard.chapters":"Kapitel","dashboard.words":"Wörter gesamt","dashboard.published":"Veröffentlicht","dashboard.newTitle":"Neues Werk erstellen","dashboard.workTitle":"Titel","dashboard.genre":"Genre","dashboard.writingLanguage":"Schreibsprache","common.cancel":"Abbrechen","common.add":"Hinzufügen","common.save":"Speichern","common.delete":"Löschen","connections.title":"Eigene KI verbinden","work.myWorks":"Meine Werke","work.settings":"Werkeinstellungen","work.saveChapter":"Kapitel speichern","work.outline":"Handlungsplan","work.addVolume":"Band hinzufügen","work.addChapter":"Kapitel hinzufügen","work.aiPrompt":"✦ KI-Prompt aus Gliederung erstellen","work.context":"KI-Kontext dieses Kapitels","work.manage":"Verwalten","work.characters":"Figuren","work.settingsTab":"Welt","work.time":"Zeitlinie","work.logic":"Logik","memory.title":"Figuren und Story-Gedächtnis verwalten","memory.character":"Figuren","memory.relationship":"Beziehungen","memory.world":"Weltenbau","memory.timeline":"Zeitlinie","memory.logic":"Logikketten" },
  fr: { "language.label":"Langue de l’interface","nav.features":"Fonctions","nav.library":"Bibliothèque","nav.about":"À propos et mentions","auth.login":"Se connecter","auth.logout":"Se déconnecter","auth.start":"Commencer à écrire","studio.navWorks":"Œuvres","studio.navConnections":"Connexions","studio.navLibrary":"Bibliothèque","studio.privateSpace":"Espace d’écriture privé","studio.privateDefault":"Privé par défaut","dashboard.morning":"Bonjour","dashboard.afternoon":"Bon après-midi","dashboard.evening":"Bonsoir","dashboard.intro":"Chaque œuvre est un espace indépendant, visible uniquement par vous par défaut.","dashboard.import":"⇩ Importer une sauvegarde complète","dashboard.new":"＋ Nouvelle œuvre","dashboard.works":"Œuvres","dashboard.chapters":"Chapitres","dashboard.words":"Total des mots","dashboard.published":"Publiées","dashboard.newTitle":"Créer une œuvre","dashboard.workTitle":"Titre","dashboard.genre":"Genre","dashboard.writingLanguage":"Langue d’écriture","common.cancel":"Annuler","common.add":"Ajouter","common.save":"Enregistrer","common.delete":"Supprimer","connections.title":"Connectez votre propre IA","work.myWorks":"Mes œuvres","work.settings":"Paramètres de l’œuvre","work.saveChapter":"Enregistrer le chapitre","work.outline":"Plan de l’histoire","work.addVolume":"Ajouter un tome","work.addChapter":"Ajouter un chapitre","work.aiPrompt":"✦ Créer le prompt IA depuis le plan","work.context":"Contexte IA de ce chapitre","work.manage":"Gérer","work.characters":"Personnages","work.settingsTab":"Monde","work.time":"Chronologie","work.logic":"Logique","memory.title":"Gérer les personnages et la mémoire du récit","memory.character":"Personnages","memory.relationship":"Relations","memory.world":"Univers","memory.timeline":"Chronologie","memory.logic":"Chaînes logiques" },
  ja: { "language.label":"表示言語","nav.features":"機能","nav.library":"ライブラリ","nav.about":"概要・免責事項","auth.login":"ログイン","auth.logout":"ログアウト","auth.start":"執筆を始める","studio.navWorks":"作品","studio.navConnections":"接続","studio.navLibrary":"ライブラリ","studio.privateSpace":"プライベート執筆スペース","studio.privateDefault":"初期設定は非公開","dashboard.morning":"おはようございます","dashboard.afternoon":"こんにちは","dashboard.evening":"こんばんは","dashboard.intro":"作品ごとに独立したスペースです。初期設定では自分だけが閲覧できます。","dashboard.import":"⇩ 完全バックアップを読み込む","dashboard.new":"＋ 新しい作品","dashboard.works":"作品","dashboard.chapters":"章","dashboard.words":"総文字数","dashboard.published":"公開済み","dashboard.newTitle":"新しい作品を作成","dashboard.workTitle":"作品名","dashboard.genre":"ジャンル","dashboard.writingLanguage":"執筆言語","common.cancel":"キャンセル","common.add":"追加","common.save":"保存","common.delete":"削除","connections.title":"自分の AI を接続","work.myWorks":"自分の作品","work.settings":"作品設定","work.saveChapter":"章を保存","work.outline":"物語のアウトライン","work.addVolume":"巻を追加","work.addChapter":"章を追加","work.aiPrompt":"✦ アウトラインから AI プロンプトを作成","work.context":"この章の AI コンテキスト","work.manage":"管理","work.characters":"登場人物","work.settingsTab":"世界設定","work.time":"時系列","work.logic":"論理","memory.title":"登場人物と物語メモリを管理","memory.character":"登場人物","memory.relationship":"関係","memory.world":"世界設定","memory.timeline":"時系列","memory.logic":"論理チェーン" },
  pt: { "language.label":"Idioma da interface","nav.features":"Recursos","nav.library":"Biblioteca","nav.about":"Sobre e aviso legal","auth.login":"Entrar","auth.logout":"Sair","auth.start":"Começar a escrever","studio.navWorks":"Obras","studio.navConnections":"Conexões","studio.navLibrary":"Biblioteca","studio.privateSpace":"Espaço privado de escrita","studio.privateDefault":"Privado por padrão","dashboard.morning":"Bom dia","dashboard.afternoon":"Boa tarde","dashboard.evening":"Boa noite","dashboard.intro":"Cada obra é um espaço independente, visível apenas para você por padrão.","dashboard.import":"⇩ Importar backup completo","dashboard.new":"＋ Nova obra","dashboard.works":"Obras","dashboard.chapters":"Capítulos","dashboard.words":"Total de palavras","dashboard.published":"Publicadas","dashboard.newTitle":"Criar uma obra","dashboard.workTitle":"Título","dashboard.genre":"Gênero","dashboard.writingLanguage":"Idioma de escrita","common.cancel":"Cancelar","common.add":"Adicionar","common.save":"Salvar","common.delete":"Excluir","connections.title":"Conecte sua própria IA","work.myWorks":"Minhas obras","work.settings":"Configurações da obra","work.saveChapter":"Salvar capítulo","work.outline":"Esboço da história","work.addVolume":"Adicionar volume","work.addChapter":"Adicionar capítulo","work.aiPrompt":"✦ Criar prompt de IA pelo esboço","work.context":"Contexto de IA deste capítulo","work.manage":"Gerenciar","work.characters":"Personagens","work.settingsTab":"Mundo","work.time":"Linha do tempo","work.logic":"Lógica","memory.title":"Gerenciar personagens e memória da história","memory.character":"Personagens","memory.relationship":"Relações","memory.world":"Mundo","memory.timeline":"Linha do tempo","memory.logic":"Cadeias lógicas" },
  ko: { "language.label":"인터페이스 언어","nav.features":"기능","nav.library":"라이브러리","nav.about":"소개 및 면책","auth.login":"로그인","auth.logout":"로그아웃","auth.start":"글쓰기 시작","studio.navWorks":"작품","studio.navConnections":"연결","studio.navLibrary":"라이브러리","studio.privateSpace":"비공개 집필 공간","studio.privateDefault":"기본 비공개","dashboard.morning":"좋은 아침입니다","dashboard.afternoon":"안녕하세요","dashboard.evening":"좋은 저녁입니다","dashboard.intro":"각 작품은 독립된 공간이며 기본적으로 본인만 볼 수 있습니다.","dashboard.import":"⇩ 전체 백업 가져오기","dashboard.new":"＋ 새 작품","dashboard.works":"작품","dashboard.chapters":"장","dashboard.words":"총 단어 수","dashboard.published":"공개됨","dashboard.newTitle":"새 작품 만들기","dashboard.workTitle":"제목","dashboard.genre":"장르","dashboard.writingLanguage":"집필 언어","common.cancel":"취소","common.add":"추가","common.save":"저장","common.delete":"삭제","connections.title":"내 AI 연결","work.myWorks":"내 작품","work.settings":"작품 설정","work.saveChapter":"장 저장","work.outline":"이야기 개요","work.addVolume":"권 추가","work.addChapter":"장 추가","work.aiPrompt":"✦ 개요로 AI 프롬프트 만들기","work.context":"이 장의 AI 컨텍스트","work.manage":"관리","work.characters":"인물","work.settingsTab":"세계관","work.time":"시간선","work.logic":"논리","memory.title":"인물과 이야기 기억 관리","memory.character":"인물","memory.relationship":"관계","memory.world":"세계관","memory.timeline":"시간선","memory.logic":"논리 체인" }
};

const extendedOverrides: Partial<Record<UiLocale, Record<string, string>>> = {
  es: {
    "footer.tagline":"La estructura para la herramienta; las decisiones para el autor.","footer.product":"Producto","footer.studio":"Estudio de escritura","footer.library":"Biblioteca comunitaria","footer.notes":"Información","footer.disclaimer":"Aviso legal","footer.privacy":"Privacidad y responsabilidad","footer.important":"Importante","footer.boundary":"Este sitio solo gestiona historias, organiza prompts y ofrece acceso MCP. No proporciona ni revende servicios de IA.",
    "home.eyebrow":"Tu modelo, tu historia","home.headline":"Convierte ideas dispersas","home.headlineEm":"en un libro completo.","home.lede":"Un espacio tranquilo para gestionar esquemas, relaciones, mundos, cadenas lógicas y versiones de capítulos. Copia prompts completos a cualquier modelo o colabora con tu propio Codex mediante MCP.","home.enter":"Entrar en mi estudio","home.chatgpt":"Entrar con ChatGPT","home.explore":"Explorar la biblioteca","home.microcopy":"Herramienta gratuita · Sin créditos incluidos · Privado por defecto","home.saved":"Guardado","home.step1Title":"Crea la estructura","home.step1Body":"Ordena volúmenes, capítulos y extensiones","home.step2Title":"Añade memoria","home.step2Body":"Usa personajes, mundo y cronología cuando corresponda","home.step3Title":"Pásalo a la IA","home.step3Body":"Tú eliges qué modelo recibe el prompt","home.workflowTitle":"La IA puede ser potente. Tu proceso puede seguir claro.","home.workflowBody":"Nosotros organizamos el contexto. Tu modelo, créditos, manuscrito y decisiones siguen siendo tuyos.","home.feature1Title":"Un árbol narrativo, no una pila de archivos","home.feature1Body":"Pliega volúmenes y capítulos y marca qué debe revisarse cuando cambia el esquema.","home.feature2Title":"Contexto con límites","home.feature2Body":"Combina solo personajes, relaciones, escenas, cronología y lógica relevantes para cada capítulo.","home.feature3Title":"Compatible con cualquier modelo","home.feature3Body":"Copia prompts a ChatGPT, Gemini o un modelo local, o usa MCP con tu propio Codex.","home.libraryTitle":"Aquí se encuentran las historias que tus amigos deciden compartir.","home.browse":"Ver todas las obras →","home.noDescription":"El autor aún no ha añadido una descripción.","home.read":"Empezar a leer →","home.ctaTitle":"El siguiente capítulo empieza con una idea clara.","home.ctaBody":"Sin factura de modelo ni formatos cerrados. Crea gratis tu primera obra.","home.ctaButton":"Abrir el estudio",
    "library.title":"Biblioteca comunitaria","library.intro":"Aquí solo aparecen las obras publicadas expresamente por sus autores. Leer no requiere iniciar sesión; escribir y publicar sí.","library.emptyTitle":"La biblioteca aún está tranquila","library.emptyBody":"Aquí aparecerán las primeras historias públicas. Entra al estudio para ser uno de los primeros autores.","library.noDescription":"El autor aún no ha añadido una descripción.","library.read":"Leer obra →","reader.noDescription":"El autor aún no ha añadido una descripción.","reader.empty":"El autor aún no ha publicado capítulos.",
    "dashboard.newIntro":"Esto crea una estructura vacía y no llama a ninguna IA.","dashboard.premise":"Idea en una frase","dashboard.premisePlaceholder":"¿Quién es el protagonista, qué quiere y cuál es el obstáculo principal?","dashboard.creating":"Creando…","dashboard.createOpen":"Crear y abrir","dashboard.deleteQuestion":"¿Eliminar «{title}»?","dashboard.keep":"Conservar obra","dashboard.deletePermanent":"Eliminar definitivamente","work.private":"Borrador privado","work.public":"Publicada","work.saving":"Guardando…","work.saved":"Guardado","work.saveFailed":"Error al guardar","work.targetWords":"Extensión objetivo","work.chapterOutline":"Esquema del capítulo","work.publishChapter":"Publicar este capítulo","work.promptTitle":"Copiar a tu propio modelo","work.copyPrompt":"Copiar prompt completo","work.foundation":"Base de la obra y publicación","work.language":"Idioma de escritura","work.description":"Descripción","work.premise":"Idea central","work.style":"Reglas de escritura / guía de estilo","work.reference":"Fragmento de referencia","work.saveSettings":"Guardar ajustes"
  },
  de: {
    "footer.tagline":"Die Struktur übernimmt das Werkzeug, die Entscheidungen der Autor.","footer.product":"Produkt","footer.studio":"Schreibstudio","footer.library":"Community-Bibliothek","footer.notes":"Hinweise","footer.disclaimer":"Haftungsausschluss","footer.privacy":"Datenschutz & Verantwortung","footer.important":"Wichtig","footer.boundary":"Diese Website verwaltet Geschichten, organisiert Prompts und bietet MCP-Zugriff. Sie stellt keine KI-Modelldienste bereit und verkauft sie nicht weiter.",
    "home.eyebrow":"Dein Modell, deine Geschichte","home.headline":"Aus verstreuten Ideen","home.headlineEm":"wird ein ganzes Buch.","home.lede":"Ein ruhiger Schreibbereich für Gliederungen, Figurenbeziehungen, Weltenbau, Logikketten und Kapitelversionen. Kopiere vollständige Prompts in jedes Modell oder arbeite über MCP mit deinem eigenen Codex.","home.enter":"Mein Studio öffnen","home.chatgpt":"Mit ChatGPT anmelden","home.explore":"Bibliothek ansehen","home.microcopy":"Kostenloses Werkzeug · Keine Modellguthaben · Standardmäßig privat","home.saved":"Gespeichert","home.step1Title":"Gerüst bauen","home.step1Body":"Bände, Kapitel und Ziellängen ordnen","home.step2Title":"Erinnerung ergänzen","home.step2Body":"Figuren, Welt und Zeitlinie passend einbeziehen","home.step3Title":"An die KI übergeben","home.step3Body":"Du bestimmst das Modell","home.workflowTitle":"KI darf stark sein. Der Schreibprozess bleibt übersichtlich.","home.workflowBody":"Wir ordnen den Kontext. Modell, Guthaben, Manuskript und Veröffentlichung bleiben bei dir.","home.feature1Title":"Ein Geschichtenbaum statt Dateichaos","home.feature1Body":"Bände und Kapitel ein- und ausklappen und nötige Überarbeitungen markieren.","home.feature2Title":"Begrenzter Kontext","home.feature2Body":"Nur relevante Figuren, Beziehungen, Szenen, Zeitlinie und Logik pro Kapitel verwenden.","home.feature3Title":"Mit jedem Modell nutzbar","home.feature3Body":"Prompts für ChatGPT, Gemini oder lokale Modelle kopieren oder Codex per MCP anbinden.","home.libraryTitle":"Hier treffen sich Geschichten, die Freunde teilen möchten.","home.browse":"Alle Werke ansehen →","home.noDescription":"Noch keine Beschreibung vorhanden.","home.read":"Lesen →","home.ctaTitle":"Das nächste Kapitel beginnt mit einer klaren Idee.","home.ctaBody":"Keine Modellrechnung, kein geschlossenes Format. Erstelle dein erstes Werk kostenlos.","home.ctaButton":"Schreibstudio öffnen",
    "library.title":"Community-Bibliothek","library.intro":"Hier erscheinen nur ausdrücklich veröffentlichte Werke. Lesen ist ohne Anmeldung möglich; Schreiben und Veröffentlichen erfordern ein Konto.","library.emptyTitle":"Die Regale sind noch still","library.emptyBody":"Hier erscheinen die ersten öffentlichen Geschichten. Melde dich im Studio an und werde einer der ersten Autoren.","library.noDescription":"Noch keine Beschreibung vorhanden.","library.read":"Werk lesen →","reader.noDescription":"Noch keine Beschreibung vorhanden.","reader.empty":"Noch keine Kapitel veröffentlicht.",
    "dashboard.newIntro":"Erstellt eine leere Struktur und ruft keine KI auf.","dashboard.premise":"Prämisse in einem Satz","dashboard.premisePlaceholder":"Wer ist die Hauptfigur, was will sie und was steht ihr im Weg?","dashboard.creating":"Wird erstellt…","dashboard.createOpen":"Erstellen und öffnen","dashboard.deleteQuestion":"„{title}“ löschen?","dashboard.keep":"Werk behalten","dashboard.deletePermanent":"Dauerhaft löschen","work.private":"Privater Entwurf","work.public":"Veröffentlicht","work.saving":"Wird gespeichert…","work.saved":"Gespeichert","work.saveFailed":"Speichern fehlgeschlagen","work.targetWords":"Ziellänge","work.chapterOutline":"Kapitelgliederung","work.publishChapter":"Kapitel veröffentlichen","work.promptTitle":"In dein Modell kopieren","work.copyPrompt":"Vollständigen Prompt kopieren","work.foundation":"Werkgrundlage & Veröffentlichung","work.language":"Schreibsprache","work.description":"Beschreibung","work.premise":"Kernidee","work.style":"Schreibregeln / Stilleitfaden","work.reference":"Referenzauszug","work.saveSettings":"Einstellungen speichern"
  },
  fr: {
    "footer.tagline":"La structure à l’outil, les choix à l’auteur.","footer.product":"Produit","footer.studio":"Atelier d’écriture","footer.library":"Bibliothèque communautaire","footer.notes":"Informations","footer.disclaimer":"Mentions légales","footer.privacy":"Confidentialité et responsabilité","footer.important":"Important","footer.boundary":"Ce site gère les récits, organise les prompts et fournit un accès MCP. Il ne fournit ni ne revend aucun service de modèle IA.",
    "home.eyebrow":"Votre modèle, votre histoire","home.headline":"Transformez des idées éparses","home.headlineEm":"en un livre complet.","home.lede":"Un espace calme pour gérer plans, relations, univers, chaînes logiques et versions de chapitres. Copiez des prompts complets vers n’importe quel modèle ou collaborez avec votre propre Codex via MCP.","home.enter":"Ouvrir mon atelier","home.chatgpt":"Se connecter avec ChatGPT","home.explore":"Explorer la bibliothèque","home.microcopy":"Outil gratuit · Aucun crédit inclus · Privé par défaut","home.saved":"Enregistré","home.step1Title":"Construire l’ossature","home.step1Body":"Organiser tomes, chapitres et longueurs cibles","home.step2Title":"Ajouter la mémoire","home.step2Body":"Mobiliser personnages, univers et chronologie","home.step3Title":"Confier à l’IA","home.step3Body":"Vous choisissez le modèle destinataire","home.workflowTitle":"L’IA peut être puissante. Votre méthode peut rester claire.","home.workflowBody":"Nous organisons le contexte. Votre modèle, vos crédits, votre manuscrit et vos décisions restent les vôtres.","home.feature1Title":"Un arbre narratif, pas une pile de fichiers","home.feature1Body":"Repliez tomes et chapitres et marquez précisément ce qui doit être révisé.","home.feature2Title":"Un contexte maîtrisé","home.feature2Body":"N’incluez que les personnages, relations, scènes, chronologie et logique utiles à chaque chapitre.","home.feature3Title":"Compatible avec tous les modèles","home.feature3Body":"Copiez les prompts vers ChatGPT, Gemini ou un modèle local, ou connectez votre Codex via MCP.","home.libraryTitle":"Les histoires que vos amis choisissent de partager se rencontrent ici.","home.browse":"Voir toutes les œuvres →","home.noDescription":"L’auteur n’a pas encore ajouté de description.","home.read":"Commencer la lecture →","home.ctaTitle":"Le prochain chapitre commence par une idée claire.","home.ctaBody":"Aucune facture de modèle, aucun format verrouillé. Créez gratuitement votre première œuvre.","home.ctaButton":"Ouvrir l’atelier",
    "library.title":"Bibliothèque communautaire","library.intro":"Seules les œuvres publiées volontairement par leurs auteurs apparaissent ici. La lecture est libre; écrire et publier nécessitent un compte.","library.emptyTitle":"Les rayons sont encore calmes","library.emptyBody":"Les premières histoires publiques apparaîtront ici. Connectez-vous à l’atelier pour devenir l’un des premiers auteurs.","library.noDescription":"L’auteur n’a pas encore ajouté de description.","library.read":"Lire l’œuvre →","reader.noDescription":"L’auteur n’a pas encore ajouté de description.","reader.empty":"L’auteur n’a encore publié aucun chapitre.",
    "dashboard.newIntro":"Crée une structure vide sans appeler d’IA.","dashboard.premise":"Idée en une phrase","dashboard.premisePlaceholder":"Qui est le protagoniste, que veut-il et quel est l’obstacle principal ?","dashboard.creating":"Création…","dashboard.createOpen":"Créer et ouvrir","dashboard.deleteQuestion":"Supprimer « {title} » ?","dashboard.keep":"Conserver l’œuvre","dashboard.deletePermanent":"Supprimer définitivement","work.private":"Brouillon privé","work.public":"Publiée","work.saving":"Enregistrement…","work.saved":"Enregistré","work.saveFailed":"Échec de l’enregistrement","work.targetWords":"Longueur cible","work.chapterOutline":"Plan du chapitre","work.publishChapter":"Publier ce chapitre","work.promptTitle":"Copier vers votre modèle","work.copyPrompt":"Copier le prompt complet","work.foundation":"Fondations et publication","work.language":"Langue d’écriture","work.description":"Description","work.premise":"Idée centrale","work.style":"Règles d’écriture / guide de style","work.reference":"Extrait de référence","work.saveSettings":"Enregistrer les paramètres"
  },
  ja: {
    "footer.tagline":"構成はツールに、選択は作者に。","footer.product":"製品","footer.studio":"執筆スタジオ","footer.library":"コミュニティライブラリ","footer.notes":"ご案内","footer.disclaimer":"免責事項","footer.privacy":"プライバシーと責任","footer.important":"重要","footer.boundary":"本サイトは作品管理、プロンプト整理、MCP 接続のみを提供し、AI モデルサービスの提供・再販売は行いません。",
    "home.eyebrow":"モデルも物語もあなたのもの","home.headline":"散らばったアイデアを","home.headlineEm":"一冊の本へ。","home.lede":"アウトライン、人物関係、世界観、論理チェーン、章の版を静かに管理する執筆空間。完全なプロンプトを任意のモデルへコピーするか、MCP 経由で自分の Codex と共同作業できます。","home.enter":"スタジオを開く","home.chatgpt":"ChatGPT でログイン","home.explore":"ライブラリを見る","home.microcopy":"無料の管理ツール · モデル枠は含みません · 初期設定は非公開","home.saved":"保存済み","home.step1Title":"骨組みを作る","home.step1Body":"巻・章・目標文字数を整理","home.step2Title":"物語の記憶を足す","home.step2Body":"人物・設定・時系列を必要な章へ","home.step3Title":"AI に渡す","home.step3Body":"どのモデルへ送るかはあなたが決定","home.workflowTitle":"AI は強力でも、執筆手順は明快に。","home.workflowBody":"私たちは文脈を整理するだけ。モデル、利用枠、原稿、公開の判断は常にあなたのものです。","home.feature1Title":"ファイルの山ではなく物語の木","home.feature1Body":"巻と章を折りたたみ、アウトライン変更後に更新が必要な章を明確にします。","home.feature2Title":"境界のあるコンテキスト","home.feature2Body":"章ごとに必要な人物、関係、場面、時系列、論理だけを組み合わせます。","home.feature3Title":"どのモデルでも利用可能","home.feature3Body":"ChatGPT、Gemini、ローカルモデルへコピー、または MCP で自分の Codex を接続できます。","home.libraryTitle":"友人が公開した物語が、ここで出会います。","home.browse":"すべての作品を見る →","home.noDescription":"作者はまだ紹介文を追加していません。","home.read":"読み始める →","home.ctaTitle":"次の章は、明確なアイデアから。","home.ctaBody":"モデル料金も形式の縛りもありません。最初の作品を無料で作りましょう。","home.ctaButton":"執筆スタジオを開く",
    "library.title":"コミュニティライブラリ","library.intro":"作者が明示的に公開した作品だけを表示します。閲覧はログイン不要、執筆と公開にはログインが必要です。","library.emptyTitle":"書棚はまだ静かです","library.emptyBody":"最初の公開作品がここに並びます。スタジオにログインして最初の作者の一人になれます。","library.noDescription":"作者はまだ紹介文を追加していません。","library.read":"作品を読む →","reader.noDescription":"作者はまだ紹介文を追加していません。","reader.empty":"公開済みの章はまだありません。",
    "dashboard.newIntro":"空の構造だけを作成し、AI は呼び出しません。","dashboard.premise":"一文の構想","dashboard.premisePlaceholder":"主人公は誰で、何を望み、最大の障害は何ですか？","dashboard.creating":"作成中…","dashboard.createOpen":"作成して開く","dashboard.deleteQuestion":"「{title}」を削除しますか？","dashboard.keep":"作品を残す","dashboard.deletePermanent":"完全に削除","work.private":"非公開下書き","work.public":"公開済み","work.saving":"保存中…","work.saved":"保存済み","work.saveFailed":"保存に失敗","work.targetWords":"目標文字数","work.chapterOutline":"章のアウトライン","work.publishChapter":"この章を公開","work.promptTitle":"自分のモデルへコピー","work.copyPrompt":"完全なプロンプトをコピー","work.foundation":"作品の基盤と公開","work.language":"執筆言語","work.description":"紹介文","work.premise":"核となる構想","work.style":"執筆ルール / スタイルガイド","work.reference":"参考抜粋","work.saveSettings":"設定を保存"
  },
  pt: {
    "footer.tagline":"A estrutura fica com a ferramenta; as escolhas, com o autor.","footer.product":"Produto","footer.studio":"Estúdio de escrita","footer.library":"Biblioteca comunitária","footer.notes":"Informações","footer.disclaimer":"Aviso legal","footer.privacy":"Privacidade e responsabilidade","footer.important":"Importante","footer.boundary":"Este site apenas gerencia histórias, organiza prompts e oferece acesso MCP. Não fornece nem revende serviços de modelos de IA.",
    "home.eyebrow":"Seu modelo, sua história","home.headline":"Transforme ideias soltas","home.headlineEm":"em um livro completo.","home.lede":"Um espaço tranquilo para gerenciar esboços, relações, mundo, cadeias lógicas e versões de capítulos. Copie prompts completos para qualquer modelo ou colabore com seu próprio Codex via MCP.","home.enter":"Entrar no meu estúdio","home.chatgpt":"Entrar com ChatGPT","home.explore":"Explorar a biblioteca","home.microcopy":"Ferramenta gratuita · Sem créditos incluídos · Privado por padrão","home.saved":"Salvo","home.step1Title":"Monte a estrutura","home.step1Body":"Organize volumes, capítulos e metas","home.step2Title":"Adicione memória","home.step2Body":"Use personagens, mundo e linha do tempo","home.step3Title":"Entregue à IA","home.step3Body":"Você escolhe qual modelo recebe o prompt","home.workflowTitle":"A IA pode ser poderosa. Seu processo pode continuar claro.","home.workflowBody":"Nós organizamos o contexto. Seu modelo, créditos, manuscrito e decisões continuam seus.","home.feature1Title":"Uma árvore narrativa, não uma pilha de arquivos","home.feature1Body":"Recolha volumes e capítulos e marque o que precisa ser revisto após mudanças no esboço.","home.feature2Title":"Contexto com limites","home.feature2Body":"Combine apenas personagens, relações, cenas, cronologia e lógica relevantes para cada capítulo.","home.feature3Title":"Funciona com qualquer modelo","home.feature3Body":"Copie prompts para ChatGPT, Gemini ou modelo local, ou conecte seu Codex por MCP.","home.libraryTitle":"As histórias que amigos escolhem compartilhar se encontram aqui.","home.browse":"Ver todas as obras →","home.noDescription":"O autor ainda não adicionou uma descrição.","home.read":"Começar a ler →","home.ctaTitle":"O próximo capítulo começa com uma ideia clara.","home.ctaBody":"Sem conta de modelo e sem formato fechado. Crie sua primeira obra gratuitamente.","home.ctaButton":"Abrir o estúdio",
    "library.title":"Biblioteca comunitária","library.intro":"Apenas obras publicadas explicitamente pelos autores aparecem aqui. A leitura não exige login; escrever e publicar exigem.","library.emptyTitle":"As estantes ainda estão quietas","library.emptyBody":"As primeiras histórias públicas aparecerão aqui. Entre no estúdio para ser um dos primeiros autores.","library.noDescription":"O autor ainda não adicionou uma descrição.","library.read":"Ler obra →","reader.noDescription":"O autor ainda não adicionou uma descrição.","reader.empty":"O autor ainda não publicou capítulos.",
    "dashboard.newIntro":"Cria uma estrutura vazia e não chama nenhuma IA.","dashboard.premise":"Ideia em uma frase","dashboard.premisePlaceholder":"Quem é o protagonista, o que deseja e qual é o principal obstáculo?","dashboard.creating":"Criando…","dashboard.createOpen":"Criar e abrir","dashboard.deleteQuestion":"Excluir “{title}”?","dashboard.keep":"Manter obra","dashboard.deletePermanent":"Excluir permanentemente","work.private":"Rascunho privado","work.public":"Publicada","work.saving":"Salvando…","work.saved":"Salvo","work.saveFailed":"Falha ao salvar","work.targetWords":"Extensão alvo","work.chapterOutline":"Esboço do capítulo","work.publishChapter":"Publicar este capítulo","work.promptTitle":"Copiar para seu modelo","work.copyPrompt":"Copiar prompt completo","work.foundation":"Base da obra e publicação","work.language":"Idioma de escrita","work.description":"Descrição","work.premise":"Ideia central","work.style":"Regras de escrita / guia de estilo","work.reference":"Trecho de referência","work.saveSettings":"Salvar configurações"
  },
  ko: {
    "footer.tagline":"구조는 도구에, 선택은 작가에게.","footer.product":"제품","footer.studio":"집필 스튜디오","footer.library":"커뮤니티 라이브러리","footer.notes":"안내","footer.disclaimer":"면책 조항","footer.privacy":"개인정보와 콘텐츠 책임","footer.important":"중요","footer.boundary":"이 사이트는 작품 관리, 프롬프트 정리, MCP 연결만 제공하며 AI 모델 서비스를 제공하거나 재판매하지 않습니다.",
    "home.eyebrow":"내 모델, 내 이야기","home.headline":"흩어진 아이디어를","home.headlineEm":"한 권의 책으로.","home.lede":"개요, 인물 관계, 세계관, 논리 체인, 장 버전을 차분하게 관리하는 집필 공간입니다. 완성된 프롬프트를 원하는 모델에 복사하거나 MCP로 자신의 Codex와 협업하세요.","home.enter":"내 스튜디오 열기","home.chatgpt":"ChatGPT로 로그인","home.explore":"라이브러리 둘러보기","home.microcopy":"무료 관리 도구 · 모델 크레딧 미포함 · 기본 비공개","home.saved":"저장됨","home.step1Title":"뼈대 만들기","home.step1Body":"권, 장, 목표 분량 정리","home.step2Title":"이야기 기억 추가","home.step2Body":"인물, 설정, 시간선을 필요한 장에 적용","home.step3Title":"AI에 전달","home.step3Body":"어떤 모델에 보낼지 직접 선택","home.workflowTitle":"AI는 강력해도 집필 과정은 명확하게.","home.workflowBody":"우리는 맥락만 정리합니다. 모델, 크레딧, 원고, 공개 결정은 언제나 작가의 것입니다.","home.feature1Title":"파일 더미가 아닌 이야기 트리","home.feature1Body":"권과 장을 접고 펼치며 개요 변경 후 수정이 필요한 장을 표시합니다.","home.feature2Title":"경계가 있는 컨텍스트","home.feature2Body":"각 장에 필요한 인물, 관계, 장면, 시간선, 논리만 조합합니다.","home.feature3Title":"어떤 모델과도 사용 가능","home.feature3Body":"ChatGPT, Gemini, 로컬 모델에 복사하거나 MCP로 자신의 Codex를 연결하세요.","home.libraryTitle":"친구들이 공개한 이야기가 이곳에서 만납니다.","home.browse":"모든 작품 보기 →","home.noDescription":"작가가 아직 소개를 추가하지 않았습니다.","home.read":"읽기 시작 →","home.ctaTitle":"다음 장은 명확한 아이디어에서 시작됩니다.","home.ctaBody":"모델 요금도 형식 잠금도 없습니다. 첫 작품을 무료로 만들어 보세요.","home.ctaButton":"집필 스튜디오 열기",
    "library.title":"커뮤니티 라이브러리","library.intro":"작가가 명시적으로 공개한 작품만 표시됩니다. 읽기는 로그인 없이 가능하며 집필과 공개에는 로그인이 필요합니다.","library.emptyTitle":"서가가 아직 조용합니다","library.emptyBody":"첫 공개 이야기가 이곳에 나타납니다. 스튜디오에 로그인해 첫 작가 중 한 명이 되어 보세요.","library.noDescription":"작가가 아직 소개를 추가하지 않았습니다.","library.read":"작품 읽기 →","reader.noDescription":"작가가 아직 소개를 추가하지 않았습니다.","reader.empty":"아직 공개된 장이 없습니다.",
    "dashboard.newIntro":"빈 구조만 만들며 AI를 호출하지 않습니다.","dashboard.premise":"한 문장 구상","dashboard.premisePlaceholder":"주인공은 누구이며 무엇을 원하고 가장 큰 장애물은 무엇인가요?","dashboard.creating":"만드는 중…","dashboard.createOpen":"만들고 열기","dashboard.deleteQuestion":"‘{title}’을 삭제할까요?","dashboard.keep":"작품 유지","dashboard.deletePermanent":"영구 삭제","work.private":"비공개 초안","work.public":"공개됨","work.saving":"저장 중…","work.saved":"저장됨","work.saveFailed":"저장 실패","work.targetWords":"목표 분량","work.chapterOutline":"장 개요","work.publishChapter":"이 장 공개","work.promptTitle":"내 모델로 복사","work.copyPrompt":"전체 프롬프트 복사","work.foundation":"작품 기반과 공개","work.language":"집필 언어","work.description":"소개","work.premise":"핵심 구상","work.style":"집필 규칙 / 스타일 가이드","work.reference":"참고 발췌","work.saveSettings":"설정 저장"
  }
};

export function translate(locale: UiLocale, key: string, vars?: TranslationVars): string {
  let value = extendedOverrides[locale]?.[key] ?? overrides[locale]?.[key] ?? en[key] ?? key;
  if (vars) for (const [name, replacement] of Object.entries(vars)) value = value.replaceAll(`{${name}}`, String(replacement));
  return value;
}
